package com.mall.admin.model.dao.ump;

import java.util.List;
import java.util.Map;

import com.mall.admin.vo.ump.CouponDetail;
import com.mall.admin.vo.ump.CouponRewardsInfo;
import com.mall.admin.vo.ump.MallIni;



public interface UMPCouponDetailDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_detail
     *
     * @mbggenerated Wed Jul 29 16:21:37 CST 2015
     */
    int deleteByPrimaryKey(Long couponDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_detail
     *
     * @mbggenerated Wed Jul 29 16:21:37 CST 2015
     */
    int insert(CouponDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_detail
     *
     * @mbggenerated Wed Jul 29 16:21:37 CST 2015
     */
    int insertSelective(CouponDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_detail
     *
     * @mbggenerated Wed Jul 29 16:21:37 CST 2015
     */
    CouponDetail selectByPrimaryKey(Long couponDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_detail
     *
     * @mbggenerated Wed Jul 29 16:21:37 CST 2015
     */
    int updateByPrimaryKeySelective(CouponDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_detail
     *
     * @mbggenerated Wed Jul 29 16:21:37 CST 2015
     */
    int updateByPrimaryKey(CouponDetail record);
    
    
    int updateAUserIdWhenNull(Long couponBatchId,Long userId);
    
    /**
	 * @param map
	 * @return
	 */
	List<CouponRewardsInfo> getCouponRewardsInfo(Map<String, Object> map);
	
	/**
	 * @param map
	 * @return
	 */
	Integer getCouponRewardsInfoCount(Map<String, Object> map);

	/**
	 * @param value
	 * @return
	 */
	List<MallIni> getSwitchFromMallIni(Map<String, Object> map);

	/**
	 * @param map
	 * @return
	 */
	Integer getSwitchFromMallIniCount(Map<String, Object> map);

	/**
	 * @param name
	 * @param value
	 * @return
	 */
	Integer updateSwitchFromMallIni(String name, String value);
}