package com.mall.admin.model.dao.ump;

import java.util.List;
import java.util.Map;

import com.mall.admin.vo.ump.Coupon;
import com.mall.admin.vo.ump.CouponBatch;
import com.mall.admin.vo.ump.CouponRewardsInfo;



public interface UMPCouponBatchDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_batch
     *
     * @mbggenerated Wed Jul 29 16:20:34 CST 2015
     */
    int deleteByPrimaryKey(Long batchId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_batch
     *
     * @mbggenerated Wed Jul 29 16:20:34 CST 2015
     */
    int insert(CouponBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_batch
     *
     * @mbggenerated Wed Jul 29 16:20:34 CST 2015
     */
    int insertSelective(CouponBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_batch
     *
     * @mbggenerated Wed Jul 29 16:20:34 CST 2015
     */
    CouponBatch selectByPrimaryKey(Long batchId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_batch
     *
     * @mbggenerated Wed Jul 29 16:20:34 CST 2015
     */
    int updateByPrimaryKeySelective(CouponBatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_batch
     *
     * @mbggenerated Wed Jul 29 16:20:34 CST 2015
     */
    int updateByPrimaryKey(CouponBatch record);
    
    
    int updateCouponBatchStatus(CouponBatch couponBatch);
    
    int lockCouponBatchByActiveSend(Long couponBatchId);
    

	/**
	 * @param map
	 * @return
	 */
	List<CouponBatch> getCouponBatchList(Map<String, Object> map);

	/**
	 * @param map
	 * @return
	 */
	List<CouponBatch> getCouponBatchAndRelationList(Map<String, Object> map);

	/**
	 * @param map
	 * @return
	 */
	Integer getCountCouponBatchList(Map<String, Object> map);
	
	
	int minusOneCouponBatch(CouponBatch couponBatch);

	/**
	 * @param map
	 */
	Integer endCouponBatch(Map<String, Object> map);
	
	public void clearCouponBatchActivityId(Long activityId);
	
	/**
	 * 锁定优惠券批次，按上活动ID
	 * @param couponBatchId
	 * @param activityId
	 * @return
	 */
	int lockCouponBatchActivity(Long couponBatchId,Long activityId);

	/**
	 * @param userId
	 */
	public List<Coupon> getUserAllByPhone(Integer userId);
	
	public List<Coupon> getCouponRewardsAllByPhone(Integer userId);

}