package com.mall.admin.model.dao.ump;

import java.util.List;
import java.util.Map;

import com.mall.admin.model.pagination.PaginationInfo;
import com.mall.admin.vo.ump.CouponBatch;
import com.mall.admin.vo.ump.CouponGive;
import com.mall.admin.vo.user.User;



public interface UMPCouponGiveDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_batch
     *
     * @mbggenerated Wed Jul 29 16:20:34 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_batch
     *
     * @mbggenerated Wed Jul 29 16:20:34 CST 2015
     */
    int insert(CouponGive record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_batch
     *
     * @mbggenerated Wed Jul 29 16:20:34 CST 2015
     */
    CouponGive selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_batch
     *
     * @mbggenerated Wed Jul 29 16:20:34 CST 2015
     */
    int updateByPrimaryKeySelective(CouponGive record);
    
    
    List<CouponGive> getList(Map<String,String> param,PaginationInfo paginationInfo);
    
    public int updateStatusAndMsg(CouponGive record);    
    
}