package com.mall.admin.model.dao.ump;

import com.mall.admin.vo.ump.CouponRestrict;


public interface UMPCouponRestrictDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_restrict
     *
     * @mbggenerated Wed Jul 29 16:21:20 CST 2015
     */
    int deleteByPrimaryKey(Long restrictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_restrict
     *
     * @mbggenerated Wed Jul 29 16:21:20 CST 2015
     */
    int insert(CouponRestrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_restrict
     *
     * @mbggenerated Wed Jul 29 16:21:20 CST 2015
     */
    int insertSelective(CouponRestrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_restrict
     *
     * @mbggenerated Wed Jul 29 16:21:20 CST 2015
     */
    CouponRestrict selectByPrimaryKey(Long restrictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_restrict
     *
     * @mbggenerated Wed Jul 29 16:21:20 CST 2015
     */
    int updateByPrimaryKeySelective(CouponRestrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_restrict
     *
     * @mbggenerated Wed Jul 29 16:21:20 CST 2015
     */
    int updateByPrimaryKey(CouponRestrict record);
}