package com.mall.admin.model.dao.subsribe;

import com.mall.admin.model.pagination.PaginationInfo;
import com.mall.admin.vo.subscribe.SubscribeDetail;
import com.mall.admin.vo.subscribe.SubscribeDetailExample;
import com.mall.admin.vo.ump.CouponGive;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SubscribeDetailDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_subscribe_detail
     *
     * @mbggenerated Mon Aug 31 14:17:49 CST 2015
     */
    int countByExample(SubscribeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_subscribe_detail
     *
     * @mbggenerated Mon Aug 31 14:17:49 CST 2015
     */
    int deleteByExample(SubscribeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_subscribe_detail
     *
     * @mbggenerated Mon Aug 31 14:17:49 CST 2015
     */
    int deleteByPrimaryKey(Long subscribeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_subscribe_detail
     *
     * @mbggenerated Mon Aug 31 14:17:49 CST 2015
     */
    int insert(SubscribeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_subscribe_detail
     *
     * @mbggenerated Mon Aug 31 14:17:49 CST 2015
     */
    int insertSelective(SubscribeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_subscribe_detail
     *
     * @mbggenerated Mon Aug 31 14:17:49 CST 2015
     */
    List<SubscribeDetail> selectByExample(SubscribeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_subscribe_detail
     *
     * @mbggenerated Mon Aug 31 14:17:49 CST 2015
     */
    SubscribeDetail selectByPrimaryKey(Long subscribeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_subscribe_detail
     *
     * @mbggenerated Mon Aug 31 14:17:49 CST 2015
     */
    int updateByExampleSelective(@Param("record") SubscribeDetail record, @Param("example") SubscribeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_subscribe_detail
     *
     * @mbggenerated Mon Aug 31 14:17:49 CST 2015
     */
    int updateByExample(@Param("record") SubscribeDetail record, @Param("example") SubscribeDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_subscribe_detail
     *
     * @mbggenerated Mon Aug 31 14:17:49 CST 2015
     */
    int updateByPrimaryKeySelective(SubscribeDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_subscribe_detail
     *
     * @mbggenerated Mon Aug 31 14:17:49 CST 2015
     */
    int updateByPrimaryKey(SubscribeDetail record);
    
    List<SubscribeDetail> getList(Map<String,Object> param,PaginationInfo paginationInfo);
}