package com.mall.admin.vo.order;

import java.util.Date;

public class Withdraw {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.id
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.user_id
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.order_id
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.order_detail_id
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private Long orderDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.sku_id
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private Long skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.sku_name
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private String skuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.sku_unit_price
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private Integer skuUnitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.sku_buy_num
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private Integer skuBuyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.sku_withdraw_num
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private Integer skuWithdrawNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.order_create_time
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private Date orderCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.reason
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.orderTotalPay
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private Integer ordertotalpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.collegeName
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private String collegename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.receiverName
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private String receivername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.receiverPhone
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private String receiverphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.transaction_id
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private String transactionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.firstSub
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private Integer firstsub;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.fullSub
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private Integer fullsub;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.createTime
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.updateTime
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.operator
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private Long operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.onlinePay
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private Integer onlinepay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.onlinePayType
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private Integer onlinepaytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.coupon
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private Integer coupon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_withdraw.operatoruser
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    private String operatoruser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.id
     *
     * @return the value of tb_withdraw.id
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.id
     *
     * @param id the value for tb_withdraw.id
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.user_id
     *
     * @return the value of tb_withdraw.user_id
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.user_id
     *
     * @param userId the value for tb_withdraw.user_id
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.order_id
     *
     * @return the value of tb_withdraw.order_id
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.order_id
     *
     * @param orderId the value for tb_withdraw.order_id
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.order_detail_id
     *
     * @return the value of tb_withdraw.order_detail_id
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public Long getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.order_detail_id
     *
     * @param orderDetailId the value for tb_withdraw.order_detail_id
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setOrderDetailId(Long orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.sku_id
     *
     * @return the value of tb_withdraw.sku_id
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.sku_id
     *
     * @param skuId the value for tb_withdraw.sku_id
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.sku_name
     *
     * @return the value of tb_withdraw.sku_name
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.sku_name
     *
     * @param skuName the value for tb_withdraw.sku_name
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setSkuName(String skuName) {
        this.skuName = skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.sku_unit_price
     *
     * @return the value of tb_withdraw.sku_unit_price
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public Integer getSkuUnitPrice() {
        return skuUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.sku_unit_price
     *
     * @param skuUnitPrice the value for tb_withdraw.sku_unit_price
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setSkuUnitPrice(Integer skuUnitPrice) {
        this.skuUnitPrice = skuUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.sku_buy_num
     *
     * @return the value of tb_withdraw.sku_buy_num
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public Integer getSkuBuyNum() {
        return skuBuyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.sku_buy_num
     *
     * @param skuBuyNum the value for tb_withdraw.sku_buy_num
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setSkuBuyNum(Integer skuBuyNum) {
        this.skuBuyNum = skuBuyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.sku_withdraw_num
     *
     * @return the value of tb_withdraw.sku_withdraw_num
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public Integer getSkuWithdrawNum() {
        return skuWithdrawNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.sku_withdraw_num
     *
     * @param skuWithdrawNum the value for tb_withdraw.sku_withdraw_num
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setSkuWithdrawNum(Integer skuWithdrawNum) {
        this.skuWithdrawNum = skuWithdrawNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.order_create_time
     *
     * @return the value of tb_withdraw.order_create_time
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public Date getOrderCreateTime() {
        return orderCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.order_create_time
     *
     * @param orderCreateTime the value for tb_withdraw.order_create_time
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setOrderCreateTime(Date orderCreateTime) {
        this.orderCreateTime = orderCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.reason
     *
     * @return the value of tb_withdraw.reason
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.reason
     *
     * @param reason the value for tb_withdraw.reason
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.orderTotalPay
     *
     * @return the value of tb_withdraw.orderTotalPay
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public Integer getOrdertotalpay() {
        return ordertotalpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.orderTotalPay
     *
     * @param ordertotalpay the value for tb_withdraw.orderTotalPay
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setOrdertotalpay(Integer ordertotalpay) {
        this.ordertotalpay = ordertotalpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.collegeName
     *
     * @return the value of tb_withdraw.collegeName
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public String getCollegename() {
        return collegename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.collegeName
     *
     * @param collegename the value for tb_withdraw.collegeName
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setCollegename(String collegename) {
        this.collegename = collegename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.receiverName
     *
     * @return the value of tb_withdraw.receiverName
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public String getReceivername() {
        return receivername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.receiverName
     *
     * @param receivername the value for tb_withdraw.receiverName
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setReceivername(String receivername) {
        this.receivername = receivername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.receiverPhone
     *
     * @return the value of tb_withdraw.receiverPhone
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public String getReceiverphone() {
        return receiverphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.receiverPhone
     *
     * @param receiverphone the value for tb_withdraw.receiverPhone
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setReceiverphone(String receiverphone) {
        this.receiverphone = receiverphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.transaction_id
     *
     * @return the value of tb_withdraw.transaction_id
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.transaction_id
     *
     * @param transactionId the value for tb_withdraw.transaction_id
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.firstSub
     *
     * @return the value of tb_withdraw.firstSub
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public Integer getFirstsub() {
        return firstsub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.firstSub
     *
     * @param firstsub the value for tb_withdraw.firstSub
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setFirstsub(Integer firstsub) {
        this.firstsub = firstsub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.fullSub
     *
     * @return the value of tb_withdraw.fullSub
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public Integer getFullsub() {
        return fullsub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.fullSub
     *
     * @param fullsub the value for tb_withdraw.fullSub
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setFullsub(Integer fullsub) {
        this.fullsub = fullsub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.createTime
     *
     * @return the value of tb_withdraw.createTime
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.createTime
     *
     * @param createtime the value for tb_withdraw.createTime
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.updateTime
     *
     * @return the value of tb_withdraw.updateTime
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.updateTime
     *
     * @param updatetime the value for tb_withdraw.updateTime
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.operator
     *
     * @return the value of tb_withdraw.operator
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public Long getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.operator
     *
     * @param operator the value for tb_withdraw.operator
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setOperator(Long operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.onlinePay
     *
     * @return the value of tb_withdraw.onlinePay
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public Integer getOnlinepay() {
        return onlinepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.onlinePay
     *
     * @param onlinepay the value for tb_withdraw.onlinePay
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setOnlinepay(Integer onlinepay) {
        this.onlinepay = onlinepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.onlinePayType
     *
     * @return the value of tb_withdraw.onlinePayType
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public Integer getOnlinepaytype() {
        return onlinepaytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.onlinePayType
     *
     * @param onlinepaytype the value for tb_withdraw.onlinePayType
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setOnlinepaytype(Integer onlinepaytype) {
        this.onlinepaytype = onlinepaytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.coupon
     *
     * @return the value of tb_withdraw.coupon
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public Integer getCoupon() {
        return coupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.coupon
     *
     * @param coupon the value for tb_withdraw.coupon
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setCoupon(Integer coupon) {
        this.coupon = coupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_withdraw.operatoruser
     *
     * @return the value of tb_withdraw.operatoruser
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public String getOperatoruser() {
        return operatoruser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_withdraw.operatoruser
     *
     * @param operatoruser the value for tb_withdraw.operatoruser
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setOperatoruser(String operatoruser) {
        this.operatoruser = operatoruser;
    }
}