package com.mall.admin.vo.order;

import com.mall.admin.vo.order.Withdraw;
import com.mall.admin.vo.order.WithdrawExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WithdrawMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    int countByExample(WithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    int deleteByExample(WithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    int insert(Withdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    int insertSelective(Withdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    List<Withdraw> selectByExample(WithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    Withdraw selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    int updateByExampleSelective(@Param("record") Withdraw record, @Param("example") WithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    int updateByExample(@Param("record") Withdraw record, @Param("example") WithdrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    int updateByPrimaryKeySelective(Withdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    int updateByPrimaryKey(Withdraw record);
}