package com.mall.admin.vo.order;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WithdrawExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public WithdrawExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Long value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Long value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Long value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Long value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Long> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Long> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Long value1, Long value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdIsNull() {
            addCriterion("order_detail_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdIsNotNull() {
            addCriterion("order_detail_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdEqualTo(Long value) {
            addCriterion("order_detail_id =", value, "orderDetailId");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdNotEqualTo(Long value) {
            addCriterion("order_detail_id <>", value, "orderDetailId");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdGreaterThan(Long value) {
            addCriterion("order_detail_id >", value, "orderDetailId");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdGreaterThanOrEqualTo(Long value) {
            addCriterion("order_detail_id >=", value, "orderDetailId");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdLessThan(Long value) {
            addCriterion("order_detail_id <", value, "orderDetailId");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdLessThanOrEqualTo(Long value) {
            addCriterion("order_detail_id <=", value, "orderDetailId");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdIn(List<Long> values) {
            addCriterion("order_detail_id in", values, "orderDetailId");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdNotIn(List<Long> values) {
            addCriterion("order_detail_id not in", values, "orderDetailId");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdBetween(Long value1, Long value2) {
            addCriterion("order_detail_id between", value1, value2, "orderDetailId");
            return (Criteria) this;
        }

        public Criteria andOrderDetailIdNotBetween(Long value1, Long value2) {
            addCriterion("order_detail_id not between", value1, value2, "orderDetailId");
            return (Criteria) this;
        }

        public Criteria andSkuIdIsNull() {
            addCriterion("sku_id is null");
            return (Criteria) this;
        }

        public Criteria andSkuIdIsNotNull() {
            addCriterion("sku_id is not null");
            return (Criteria) this;
        }

        public Criteria andSkuIdEqualTo(Long value) {
            addCriterion("sku_id =", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotEqualTo(Long value) {
            addCriterion("sku_id <>", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThan(Long value) {
            addCriterion("sku_id >", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sku_id >=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThan(Long value) {
            addCriterion("sku_id <", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThanOrEqualTo(Long value) {
            addCriterion("sku_id <=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdIn(List<Long> values) {
            addCriterion("sku_id in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotIn(List<Long> values) {
            addCriterion("sku_id not in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdBetween(Long value1, Long value2) {
            addCriterion("sku_id between", value1, value2, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotBetween(Long value1, Long value2) {
            addCriterion("sku_id not between", value1, value2, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuNameIsNull() {
            addCriterion("sku_name is null");
            return (Criteria) this;
        }

        public Criteria andSkuNameIsNotNull() {
            addCriterion("sku_name is not null");
            return (Criteria) this;
        }

        public Criteria andSkuNameEqualTo(String value) {
            addCriterion("sku_name =", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotEqualTo(String value) {
            addCriterion("sku_name <>", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameGreaterThan(String value) {
            addCriterion("sku_name >", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameGreaterThanOrEqualTo(String value) {
            addCriterion("sku_name >=", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLessThan(String value) {
            addCriterion("sku_name <", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLessThanOrEqualTo(String value) {
            addCriterion("sku_name <=", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLike(String value) {
            addCriterion("sku_name like", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotLike(String value) {
            addCriterion("sku_name not like", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameIn(List<String> values) {
            addCriterion("sku_name in", values, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotIn(List<String> values) {
            addCriterion("sku_name not in", values, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameBetween(String value1, String value2) {
            addCriterion("sku_name between", value1, value2, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotBetween(String value1, String value2) {
            addCriterion("sku_name not between", value1, value2, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuUnitPriceIsNull() {
            addCriterion("sku_unit_price is null");
            return (Criteria) this;
        }

        public Criteria andSkuUnitPriceIsNotNull() {
            addCriterion("sku_unit_price is not null");
            return (Criteria) this;
        }

        public Criteria andSkuUnitPriceEqualTo(Integer value) {
            addCriterion("sku_unit_price =", value, "skuUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSkuUnitPriceNotEqualTo(Integer value) {
            addCriterion("sku_unit_price <>", value, "skuUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSkuUnitPriceGreaterThan(Integer value) {
            addCriterion("sku_unit_price >", value, "skuUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSkuUnitPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("sku_unit_price >=", value, "skuUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSkuUnitPriceLessThan(Integer value) {
            addCriterion("sku_unit_price <", value, "skuUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSkuUnitPriceLessThanOrEqualTo(Integer value) {
            addCriterion("sku_unit_price <=", value, "skuUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSkuUnitPriceIn(List<Integer> values) {
            addCriterion("sku_unit_price in", values, "skuUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSkuUnitPriceNotIn(List<Integer> values) {
            addCriterion("sku_unit_price not in", values, "skuUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSkuUnitPriceBetween(Integer value1, Integer value2) {
            addCriterion("sku_unit_price between", value1, value2, "skuUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSkuUnitPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("sku_unit_price not between", value1, value2, "skuUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSkuBuyNumIsNull() {
            addCriterion("sku_buy_num is null");
            return (Criteria) this;
        }

        public Criteria andSkuBuyNumIsNotNull() {
            addCriterion("sku_buy_num is not null");
            return (Criteria) this;
        }

        public Criteria andSkuBuyNumEqualTo(Integer value) {
            addCriterion("sku_buy_num =", value, "skuBuyNum");
            return (Criteria) this;
        }

        public Criteria andSkuBuyNumNotEqualTo(Integer value) {
            addCriterion("sku_buy_num <>", value, "skuBuyNum");
            return (Criteria) this;
        }

        public Criteria andSkuBuyNumGreaterThan(Integer value) {
            addCriterion("sku_buy_num >", value, "skuBuyNum");
            return (Criteria) this;
        }

        public Criteria andSkuBuyNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("sku_buy_num >=", value, "skuBuyNum");
            return (Criteria) this;
        }

        public Criteria andSkuBuyNumLessThan(Integer value) {
            addCriterion("sku_buy_num <", value, "skuBuyNum");
            return (Criteria) this;
        }

        public Criteria andSkuBuyNumLessThanOrEqualTo(Integer value) {
            addCriterion("sku_buy_num <=", value, "skuBuyNum");
            return (Criteria) this;
        }

        public Criteria andSkuBuyNumIn(List<Integer> values) {
            addCriterion("sku_buy_num in", values, "skuBuyNum");
            return (Criteria) this;
        }

        public Criteria andSkuBuyNumNotIn(List<Integer> values) {
            addCriterion("sku_buy_num not in", values, "skuBuyNum");
            return (Criteria) this;
        }

        public Criteria andSkuBuyNumBetween(Integer value1, Integer value2) {
            addCriterion("sku_buy_num between", value1, value2, "skuBuyNum");
            return (Criteria) this;
        }

        public Criteria andSkuBuyNumNotBetween(Integer value1, Integer value2) {
            addCriterion("sku_buy_num not between", value1, value2, "skuBuyNum");
            return (Criteria) this;
        }

        public Criteria andSkuWithdrawNumIsNull() {
            addCriterion("sku_withdraw_num is null");
            return (Criteria) this;
        }

        public Criteria andSkuWithdrawNumIsNotNull() {
            addCriterion("sku_withdraw_num is not null");
            return (Criteria) this;
        }

        public Criteria andSkuWithdrawNumEqualTo(Integer value) {
            addCriterion("sku_withdraw_num =", value, "skuWithdrawNum");
            return (Criteria) this;
        }

        public Criteria andSkuWithdrawNumNotEqualTo(Integer value) {
            addCriterion("sku_withdraw_num <>", value, "skuWithdrawNum");
            return (Criteria) this;
        }

        public Criteria andSkuWithdrawNumGreaterThan(Integer value) {
            addCriterion("sku_withdraw_num >", value, "skuWithdrawNum");
            return (Criteria) this;
        }

        public Criteria andSkuWithdrawNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("sku_withdraw_num >=", value, "skuWithdrawNum");
            return (Criteria) this;
        }

        public Criteria andSkuWithdrawNumLessThan(Integer value) {
            addCriterion("sku_withdraw_num <", value, "skuWithdrawNum");
            return (Criteria) this;
        }

        public Criteria andSkuWithdrawNumLessThanOrEqualTo(Integer value) {
            addCriterion("sku_withdraw_num <=", value, "skuWithdrawNum");
            return (Criteria) this;
        }

        public Criteria andSkuWithdrawNumIn(List<Integer> values) {
            addCriterion("sku_withdraw_num in", values, "skuWithdrawNum");
            return (Criteria) this;
        }

        public Criteria andSkuWithdrawNumNotIn(List<Integer> values) {
            addCriterion("sku_withdraw_num not in", values, "skuWithdrawNum");
            return (Criteria) this;
        }

        public Criteria andSkuWithdrawNumBetween(Integer value1, Integer value2) {
            addCriterion("sku_withdraw_num between", value1, value2, "skuWithdrawNum");
            return (Criteria) this;
        }

        public Criteria andSkuWithdrawNumNotBetween(Integer value1, Integer value2) {
            addCriterion("sku_withdraw_num not between", value1, value2, "skuWithdrawNum");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeIsNull() {
            addCriterion("order_create_time is null");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeIsNotNull() {
            addCriterion("order_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeEqualTo(Date value) {
            addCriterion("order_create_time =", value, "orderCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeNotEqualTo(Date value) {
            addCriterion("order_create_time <>", value, "orderCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeGreaterThan(Date value) {
            addCriterion("order_create_time >", value, "orderCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("order_create_time >=", value, "orderCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeLessThan(Date value) {
            addCriterion("order_create_time <", value, "orderCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("order_create_time <=", value, "orderCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeIn(List<Date> values) {
            addCriterion("order_create_time in", values, "orderCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeNotIn(List<Date> values) {
            addCriterion("order_create_time not in", values, "orderCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeBetween(Date value1, Date value2) {
            addCriterion("order_create_time between", value1, value2, "orderCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("order_create_time not between", value1, value2, "orderCreateTime");
            return (Criteria) this;
        }

        public Criteria andReasonIsNull() {
            addCriterion("reason is null");
            return (Criteria) this;
        }

        public Criteria andReasonIsNotNull() {
            addCriterion("reason is not null");
            return (Criteria) this;
        }

        public Criteria andReasonEqualTo(String value) {
            addCriterion("reason =", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotEqualTo(String value) {
            addCriterion("reason <>", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThan(String value) {
            addCriterion("reason >", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThanOrEqualTo(String value) {
            addCriterion("reason >=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThan(String value) {
            addCriterion("reason <", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThanOrEqualTo(String value) {
            addCriterion("reason <=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLike(String value) {
            addCriterion("reason like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotLike(String value) {
            addCriterion("reason not like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonIn(List<String> values) {
            addCriterion("reason in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotIn(List<String> values) {
            addCriterion("reason not in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonBetween(String value1, String value2) {
            addCriterion("reason between", value1, value2, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotBetween(String value1, String value2) {
            addCriterion("reason not between", value1, value2, "reason");
            return (Criteria) this;
        }

        public Criteria andOrdertotalpayIsNull() {
            addCriterion("orderTotalPay is null");
            return (Criteria) this;
        }

        public Criteria andOrdertotalpayIsNotNull() {
            addCriterion("orderTotalPay is not null");
            return (Criteria) this;
        }

        public Criteria andOrdertotalpayEqualTo(Integer value) {
            addCriterion("orderTotalPay =", value, "ordertotalpay");
            return (Criteria) this;
        }

        public Criteria andOrdertotalpayNotEqualTo(Integer value) {
            addCriterion("orderTotalPay <>", value, "ordertotalpay");
            return (Criteria) this;
        }

        public Criteria andOrdertotalpayGreaterThan(Integer value) {
            addCriterion("orderTotalPay >", value, "ordertotalpay");
            return (Criteria) this;
        }

        public Criteria andOrdertotalpayGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderTotalPay >=", value, "ordertotalpay");
            return (Criteria) this;
        }

        public Criteria andOrdertotalpayLessThan(Integer value) {
            addCriterion("orderTotalPay <", value, "ordertotalpay");
            return (Criteria) this;
        }

        public Criteria andOrdertotalpayLessThanOrEqualTo(Integer value) {
            addCriterion("orderTotalPay <=", value, "ordertotalpay");
            return (Criteria) this;
        }

        public Criteria andOrdertotalpayIn(List<Integer> values) {
            addCriterion("orderTotalPay in", values, "ordertotalpay");
            return (Criteria) this;
        }

        public Criteria andOrdertotalpayNotIn(List<Integer> values) {
            addCriterion("orderTotalPay not in", values, "ordertotalpay");
            return (Criteria) this;
        }

        public Criteria andOrdertotalpayBetween(Integer value1, Integer value2) {
            addCriterion("orderTotalPay between", value1, value2, "ordertotalpay");
            return (Criteria) this;
        }

        public Criteria andOrdertotalpayNotBetween(Integer value1, Integer value2) {
            addCriterion("orderTotalPay not between", value1, value2, "ordertotalpay");
            return (Criteria) this;
        }

        public Criteria andCollegenameIsNull() {
            addCriterion("collegeName is null");
            return (Criteria) this;
        }

        public Criteria andCollegenameIsNotNull() {
            addCriterion("collegeName is not null");
            return (Criteria) this;
        }

        public Criteria andCollegenameEqualTo(String value) {
            addCriterion("collegeName =", value, "collegename");
            return (Criteria) this;
        }

        public Criteria andCollegenameNotEqualTo(String value) {
            addCriterion("collegeName <>", value, "collegename");
            return (Criteria) this;
        }

        public Criteria andCollegenameGreaterThan(String value) {
            addCriterion("collegeName >", value, "collegename");
            return (Criteria) this;
        }

        public Criteria andCollegenameGreaterThanOrEqualTo(String value) {
            addCriterion("collegeName >=", value, "collegename");
            return (Criteria) this;
        }

        public Criteria andCollegenameLessThan(String value) {
            addCriterion("collegeName <", value, "collegename");
            return (Criteria) this;
        }

        public Criteria andCollegenameLessThanOrEqualTo(String value) {
            addCriterion("collegeName <=", value, "collegename");
            return (Criteria) this;
        }

        public Criteria andCollegenameLike(String value) {
            addCriterion("collegeName like", value, "collegename");
            return (Criteria) this;
        }

        public Criteria andCollegenameNotLike(String value) {
            addCriterion("collegeName not like", value, "collegename");
            return (Criteria) this;
        }

        public Criteria andCollegenameIn(List<String> values) {
            addCriterion("collegeName in", values, "collegename");
            return (Criteria) this;
        }

        public Criteria andCollegenameNotIn(List<String> values) {
            addCriterion("collegeName not in", values, "collegename");
            return (Criteria) this;
        }

        public Criteria andCollegenameBetween(String value1, String value2) {
            addCriterion("collegeName between", value1, value2, "collegename");
            return (Criteria) this;
        }

        public Criteria andCollegenameNotBetween(String value1, String value2) {
            addCriterion("collegeName not between", value1, value2, "collegename");
            return (Criteria) this;
        }

        public Criteria andReceivernameIsNull() {
            addCriterion("receiverName is null");
            return (Criteria) this;
        }

        public Criteria andReceivernameIsNotNull() {
            addCriterion("receiverName is not null");
            return (Criteria) this;
        }

        public Criteria andReceivernameEqualTo(String value) {
            addCriterion("receiverName =", value, "receivername");
            return (Criteria) this;
        }

        public Criteria andReceivernameNotEqualTo(String value) {
            addCriterion("receiverName <>", value, "receivername");
            return (Criteria) this;
        }

        public Criteria andReceivernameGreaterThan(String value) {
            addCriterion("receiverName >", value, "receivername");
            return (Criteria) this;
        }

        public Criteria andReceivernameGreaterThanOrEqualTo(String value) {
            addCriterion("receiverName >=", value, "receivername");
            return (Criteria) this;
        }

        public Criteria andReceivernameLessThan(String value) {
            addCriterion("receiverName <", value, "receivername");
            return (Criteria) this;
        }

        public Criteria andReceivernameLessThanOrEqualTo(String value) {
            addCriterion("receiverName <=", value, "receivername");
            return (Criteria) this;
        }

        public Criteria andReceivernameLike(String value) {
            addCriterion("receiverName like", value, "receivername");
            return (Criteria) this;
        }

        public Criteria andReceivernameNotLike(String value) {
            addCriterion("receiverName not like", value, "receivername");
            return (Criteria) this;
        }

        public Criteria andReceivernameIn(List<String> values) {
            addCriterion("receiverName in", values, "receivername");
            return (Criteria) this;
        }

        public Criteria andReceivernameNotIn(List<String> values) {
            addCriterion("receiverName not in", values, "receivername");
            return (Criteria) this;
        }

        public Criteria andReceivernameBetween(String value1, String value2) {
            addCriterion("receiverName between", value1, value2, "receivername");
            return (Criteria) this;
        }

        public Criteria andReceivernameNotBetween(String value1, String value2) {
            addCriterion("receiverName not between", value1, value2, "receivername");
            return (Criteria) this;
        }

        public Criteria andReceiverphoneIsNull() {
            addCriterion("receiverPhone is null");
            return (Criteria) this;
        }

        public Criteria andReceiverphoneIsNotNull() {
            addCriterion("receiverPhone is not null");
            return (Criteria) this;
        }

        public Criteria andReceiverphoneEqualTo(String value) {
            addCriterion("receiverPhone =", value, "receiverphone");
            return (Criteria) this;
        }

        public Criteria andReceiverphoneNotEqualTo(String value) {
            addCriterion("receiverPhone <>", value, "receiverphone");
            return (Criteria) this;
        }

        public Criteria andReceiverphoneGreaterThan(String value) {
            addCriterion("receiverPhone >", value, "receiverphone");
            return (Criteria) this;
        }

        public Criteria andReceiverphoneGreaterThanOrEqualTo(String value) {
            addCriterion("receiverPhone >=", value, "receiverphone");
            return (Criteria) this;
        }

        public Criteria andReceiverphoneLessThan(String value) {
            addCriterion("receiverPhone <", value, "receiverphone");
            return (Criteria) this;
        }

        public Criteria andReceiverphoneLessThanOrEqualTo(String value) {
            addCriterion("receiverPhone <=", value, "receiverphone");
            return (Criteria) this;
        }

        public Criteria andReceiverphoneLike(String value) {
            addCriterion("receiverPhone like", value, "receiverphone");
            return (Criteria) this;
        }

        public Criteria andReceiverphoneNotLike(String value) {
            addCriterion("receiverPhone not like", value, "receiverphone");
            return (Criteria) this;
        }

        public Criteria andReceiverphoneIn(List<String> values) {
            addCriterion("receiverPhone in", values, "receiverphone");
            return (Criteria) this;
        }

        public Criteria andReceiverphoneNotIn(List<String> values) {
            addCriterion("receiverPhone not in", values, "receiverphone");
            return (Criteria) this;
        }

        public Criteria andReceiverphoneBetween(String value1, String value2) {
            addCriterion("receiverPhone between", value1, value2, "receiverphone");
            return (Criteria) this;
        }

        public Criteria andReceiverphoneNotBetween(String value1, String value2) {
            addCriterion("receiverPhone not between", value1, value2, "receiverphone");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIsNull() {
            addCriterion("transaction_id is null");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIsNotNull() {
            addCriterion("transaction_id is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionIdEqualTo(String value) {
            addCriterion("transaction_id =", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotEqualTo(String value) {
            addCriterion("transaction_id <>", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdGreaterThan(String value) {
            addCriterion("transaction_id >", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdGreaterThanOrEqualTo(String value) {
            addCriterion("transaction_id >=", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLessThan(String value) {
            addCriterion("transaction_id <", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLessThanOrEqualTo(String value) {
            addCriterion("transaction_id <=", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLike(String value) {
            addCriterion("transaction_id like", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotLike(String value) {
            addCriterion("transaction_id not like", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIn(List<String> values) {
            addCriterion("transaction_id in", values, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotIn(List<String> values) {
            addCriterion("transaction_id not in", values, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdBetween(String value1, String value2) {
            addCriterion("transaction_id between", value1, value2, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotBetween(String value1, String value2) {
            addCriterion("transaction_id not between", value1, value2, "transactionId");
            return (Criteria) this;
        }

        public Criteria andFirstsubIsNull() {
            addCriterion("firstSub is null");
            return (Criteria) this;
        }

        public Criteria andFirstsubIsNotNull() {
            addCriterion("firstSub is not null");
            return (Criteria) this;
        }

        public Criteria andFirstsubEqualTo(Integer value) {
            addCriterion("firstSub =", value, "firstsub");
            return (Criteria) this;
        }

        public Criteria andFirstsubNotEqualTo(Integer value) {
            addCriterion("firstSub <>", value, "firstsub");
            return (Criteria) this;
        }

        public Criteria andFirstsubGreaterThan(Integer value) {
            addCriterion("firstSub >", value, "firstsub");
            return (Criteria) this;
        }

        public Criteria andFirstsubGreaterThanOrEqualTo(Integer value) {
            addCriterion("firstSub >=", value, "firstsub");
            return (Criteria) this;
        }

        public Criteria andFirstsubLessThan(Integer value) {
            addCriterion("firstSub <", value, "firstsub");
            return (Criteria) this;
        }

        public Criteria andFirstsubLessThanOrEqualTo(Integer value) {
            addCriterion("firstSub <=", value, "firstsub");
            return (Criteria) this;
        }

        public Criteria andFirstsubIn(List<Integer> values) {
            addCriterion("firstSub in", values, "firstsub");
            return (Criteria) this;
        }

        public Criteria andFirstsubNotIn(List<Integer> values) {
            addCriterion("firstSub not in", values, "firstsub");
            return (Criteria) this;
        }

        public Criteria andFirstsubBetween(Integer value1, Integer value2) {
            addCriterion("firstSub between", value1, value2, "firstsub");
            return (Criteria) this;
        }

        public Criteria andFirstsubNotBetween(Integer value1, Integer value2) {
            addCriterion("firstSub not between", value1, value2, "firstsub");
            return (Criteria) this;
        }

        public Criteria andFullsubIsNull() {
            addCriterion("fullSub is null");
            return (Criteria) this;
        }

        public Criteria andFullsubIsNotNull() {
            addCriterion("fullSub is not null");
            return (Criteria) this;
        }

        public Criteria andFullsubEqualTo(Integer value) {
            addCriterion("fullSub =", value, "fullsub");
            return (Criteria) this;
        }

        public Criteria andFullsubNotEqualTo(Integer value) {
            addCriterion("fullSub <>", value, "fullsub");
            return (Criteria) this;
        }

        public Criteria andFullsubGreaterThan(Integer value) {
            addCriterion("fullSub >", value, "fullsub");
            return (Criteria) this;
        }

        public Criteria andFullsubGreaterThanOrEqualTo(Integer value) {
            addCriterion("fullSub >=", value, "fullsub");
            return (Criteria) this;
        }

        public Criteria andFullsubLessThan(Integer value) {
            addCriterion("fullSub <", value, "fullsub");
            return (Criteria) this;
        }

        public Criteria andFullsubLessThanOrEqualTo(Integer value) {
            addCriterion("fullSub <=", value, "fullsub");
            return (Criteria) this;
        }

        public Criteria andFullsubIn(List<Integer> values) {
            addCriterion("fullSub in", values, "fullsub");
            return (Criteria) this;
        }

        public Criteria andFullsubNotIn(List<Integer> values) {
            addCriterion("fullSub not in", values, "fullsub");
            return (Criteria) this;
        }

        public Criteria andFullsubBetween(Integer value1, Integer value2) {
            addCriterion("fullSub between", value1, value2, "fullsub");
            return (Criteria) this;
        }

        public Criteria andFullsubNotBetween(Integer value1, Integer value2) {
            addCriterion("fullSub not between", value1, value2, "fullsub");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("operator is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("operator is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(Long value) {
            addCriterion("operator =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(Long value) {
            addCriterion("operator <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(Long value) {
            addCriterion("operator >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(Long value) {
            addCriterion("operator >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(Long value) {
            addCriterion("operator <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(Long value) {
            addCriterion("operator <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<Long> values) {
            addCriterion("operator in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<Long> values) {
            addCriterion("operator not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(Long value1, Long value2) {
            addCriterion("operator between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(Long value1, Long value2) {
            addCriterion("operator not between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOnlinepayIsNull() {
            addCriterion("onlinePay is null");
            return (Criteria) this;
        }

        public Criteria andOnlinepayIsNotNull() {
            addCriterion("onlinePay is not null");
            return (Criteria) this;
        }

        public Criteria andOnlinepayEqualTo(Integer value) {
            addCriterion("onlinePay =", value, "onlinepay");
            return (Criteria) this;
        }

        public Criteria andOnlinepayNotEqualTo(Integer value) {
            addCriterion("onlinePay <>", value, "onlinepay");
            return (Criteria) this;
        }

        public Criteria andOnlinepayGreaterThan(Integer value) {
            addCriterion("onlinePay >", value, "onlinepay");
            return (Criteria) this;
        }

        public Criteria andOnlinepayGreaterThanOrEqualTo(Integer value) {
            addCriterion("onlinePay >=", value, "onlinepay");
            return (Criteria) this;
        }

        public Criteria andOnlinepayLessThan(Integer value) {
            addCriterion("onlinePay <", value, "onlinepay");
            return (Criteria) this;
        }

        public Criteria andOnlinepayLessThanOrEqualTo(Integer value) {
            addCriterion("onlinePay <=", value, "onlinepay");
            return (Criteria) this;
        }

        public Criteria andOnlinepayIn(List<Integer> values) {
            addCriterion("onlinePay in", values, "onlinepay");
            return (Criteria) this;
        }

        public Criteria andOnlinepayNotIn(List<Integer> values) {
            addCriterion("onlinePay not in", values, "onlinepay");
            return (Criteria) this;
        }

        public Criteria andOnlinepayBetween(Integer value1, Integer value2) {
            addCriterion("onlinePay between", value1, value2, "onlinepay");
            return (Criteria) this;
        }

        public Criteria andOnlinepayNotBetween(Integer value1, Integer value2) {
            addCriterion("onlinePay not between", value1, value2, "onlinepay");
            return (Criteria) this;
        }

        public Criteria andOnlinepaytypeIsNull() {
            addCriterion("onlinePayType is null");
            return (Criteria) this;
        }

        public Criteria andOnlinepaytypeIsNotNull() {
            addCriterion("onlinePayType is not null");
            return (Criteria) this;
        }

        public Criteria andOnlinepaytypeEqualTo(Integer value) {
            addCriterion("onlinePayType =", value, "onlinepaytype");
            return (Criteria) this;
        }

        public Criteria andOnlinepaytypeNotEqualTo(Integer value) {
            addCriterion("onlinePayType <>", value, "onlinepaytype");
            return (Criteria) this;
        }

        public Criteria andOnlinepaytypeGreaterThan(Integer value) {
            addCriterion("onlinePayType >", value, "onlinepaytype");
            return (Criteria) this;
        }

        public Criteria andOnlinepaytypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("onlinePayType >=", value, "onlinepaytype");
            return (Criteria) this;
        }

        public Criteria andOnlinepaytypeLessThan(Integer value) {
            addCriterion("onlinePayType <", value, "onlinepaytype");
            return (Criteria) this;
        }

        public Criteria andOnlinepaytypeLessThanOrEqualTo(Integer value) {
            addCriterion("onlinePayType <=", value, "onlinepaytype");
            return (Criteria) this;
        }

        public Criteria andOnlinepaytypeIn(List<Integer> values) {
            addCriterion("onlinePayType in", values, "onlinepaytype");
            return (Criteria) this;
        }

        public Criteria andOnlinepaytypeNotIn(List<Integer> values) {
            addCriterion("onlinePayType not in", values, "onlinepaytype");
            return (Criteria) this;
        }

        public Criteria andOnlinepaytypeBetween(Integer value1, Integer value2) {
            addCriterion("onlinePayType between", value1, value2, "onlinepaytype");
            return (Criteria) this;
        }

        public Criteria andOnlinepaytypeNotBetween(Integer value1, Integer value2) {
            addCriterion("onlinePayType not between", value1, value2, "onlinepaytype");
            return (Criteria) this;
        }

        public Criteria andCouponIsNull() {
            addCriterion("coupon is null");
            return (Criteria) this;
        }

        public Criteria andCouponIsNotNull() {
            addCriterion("coupon is not null");
            return (Criteria) this;
        }

        public Criteria andCouponEqualTo(Integer value) {
            addCriterion("coupon =", value, "coupon");
            return (Criteria) this;
        }

        public Criteria andCouponNotEqualTo(Integer value) {
            addCriterion("coupon <>", value, "coupon");
            return (Criteria) this;
        }

        public Criteria andCouponGreaterThan(Integer value) {
            addCriterion("coupon >", value, "coupon");
            return (Criteria) this;
        }

        public Criteria andCouponGreaterThanOrEqualTo(Integer value) {
            addCriterion("coupon >=", value, "coupon");
            return (Criteria) this;
        }

        public Criteria andCouponLessThan(Integer value) {
            addCriterion("coupon <", value, "coupon");
            return (Criteria) this;
        }

        public Criteria andCouponLessThanOrEqualTo(Integer value) {
            addCriterion("coupon <=", value, "coupon");
            return (Criteria) this;
        }

        public Criteria andCouponIn(List<Integer> values) {
            addCriterion("coupon in", values, "coupon");
            return (Criteria) this;
        }

        public Criteria andCouponNotIn(List<Integer> values) {
            addCriterion("coupon not in", values, "coupon");
            return (Criteria) this;
        }

        public Criteria andCouponBetween(Integer value1, Integer value2) {
            addCriterion("coupon between", value1, value2, "coupon");
            return (Criteria) this;
        }

        public Criteria andCouponNotBetween(Integer value1, Integer value2) {
            addCriterion("coupon not between", value1, value2, "coupon");
            return (Criteria) this;
        }

        public Criteria andOperatoruserIsNull() {
            addCriterion("operatoruser is null");
            return (Criteria) this;
        }

        public Criteria andOperatoruserIsNotNull() {
            addCriterion("operatoruser is not null");
            return (Criteria) this;
        }

        public Criteria andOperatoruserEqualTo(String value) {
            addCriterion("operatoruser =", value, "operatoruser");
            return (Criteria) this;
        }

        public Criteria andOperatoruserNotEqualTo(String value) {
            addCriterion("operatoruser <>", value, "operatoruser");
            return (Criteria) this;
        }

        public Criteria andOperatoruserGreaterThan(String value) {
            addCriterion("operatoruser >", value, "operatoruser");
            return (Criteria) this;
        }

        public Criteria andOperatoruserGreaterThanOrEqualTo(String value) {
            addCriterion("operatoruser >=", value, "operatoruser");
            return (Criteria) this;
        }

        public Criteria andOperatoruserLessThan(String value) {
            addCriterion("operatoruser <", value, "operatoruser");
            return (Criteria) this;
        }

        public Criteria andOperatoruserLessThanOrEqualTo(String value) {
            addCriterion("operatoruser <=", value, "operatoruser");
            return (Criteria) this;
        }

        public Criteria andOperatoruserLike(String value) {
            addCriterion("operatoruser like", value, "operatoruser");
            return (Criteria) this;
        }

        public Criteria andOperatoruserNotLike(String value) {
            addCriterion("operatoruser not like", value, "operatoruser");
            return (Criteria) this;
        }

        public Criteria andOperatoruserIn(List<String> values) {
            addCriterion("operatoruser in", values, "operatoruser");
            return (Criteria) this;
        }

        public Criteria andOperatoruserNotIn(List<String> values) {
            addCriterion("operatoruser not in", values, "operatoruser");
            return (Criteria) this;
        }

        public Criteria andOperatoruserBetween(String value1, String value2) {
            addCriterion("operatoruser between", value1, value2, "operatoruser");
            return (Criteria) this;
        }

        public Criteria andOperatoruserNotBetween(String value1, String value2) {
            addCriterion("operatoruser not between", value1, value2, "operatoruser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_withdraw
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 14 16:28:48 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_withdraw
     *
     * @mbggenerated Tue Jul 14 16:28:48 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}