package com.mall.admin.vo.storage;

import java.util.Date;

public class ApplyPayLog {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column tb_applypaylog.apply_pay_id
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	private Long applyPayId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column tb_applypaylog.apply_code
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	private String applyCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column tb_applypaylog.storage_id
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	private Long storageId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column tb_applypaylog.seller_id
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	private Long sellerId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column tb_applypaylog.sum_money
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	private Long sumMoney;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column tb_applypaylog.account_money
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	private long accountMoney;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column tb_applypaylog.record_count
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	private Integer recordCount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column tb_applypaylog.create_time
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column tb_applypaylog.pay_time
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	private Date payTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column tb_applypaylog.status
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	private Byte status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column tb_applypaylog.apply_user_id
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	private Long applyUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column tb_applypaylog.apply_user_name
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	private String applyUserName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column tb_applypaylog.pay_user_id
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	private Long payUserId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column tb_applypaylog.oa_code
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	private String oaCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds
	 * to the database column tb_applypaylog.remark
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column tb_applypaylog.apply_pay_id
	 *
	 * @return the value of tb_applypaylog.apply_pay_id
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public Long getApplyPayId() {
		return applyPayId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_applypaylog.apply_pay_id
	 *
	 * @param applyPayId
	 *                the value for tb_applypaylog.apply_pay_id
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public void setApplyPayId(Long applyPayId) {
		this.applyPayId = applyPayId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column tb_applypaylog.apply_code
	 *
	 * @return the value of tb_applypaylog.apply_code
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public String getApplyCode() {
		return applyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_applypaylog.apply_code
	 *
	 * @param applyCode
	 *                the value for tb_applypaylog.apply_code
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public void setApplyCode(String applyCode) {
		this.applyCode = applyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column tb_applypaylog.storage_id
	 *
	 * @return the value of tb_applypaylog.storage_id
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public Long getStorageId() {
		return storageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_applypaylog.storage_id
	 *
	 * @param storageId
	 *                the value for tb_applypaylog.storage_id
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public void setStorageId(Long storageId) {
		this.storageId = storageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column tb_applypaylog.seller_id
	 *
	 * @return the value of tb_applypaylog.seller_id
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public Long getSellerId() {
		return sellerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_applypaylog.seller_id
	 *
	 * @param sellerId
	 *                the value for tb_applypaylog.seller_id
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public void setSellerId(Long sellerId) {
		this.sellerId = sellerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column tb_applypaylog.sum_money
	 *
	 * @return the value of tb_applypaylog.sum_money
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public Long getSumMoney() {
		return sumMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_applypaylog.sum_money
	 *
	 * @param sumMoney
	 *                the value for tb_applypaylog.sum_money
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public void setSumMoney(Long sumMoney) {
		this.sumMoney = sumMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column tb_applypaylog.account_money
	 *
	 * @return the value of tb_applypaylog.account_money
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public Long getAccountMoney() {
		return accountMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_applypaylog.account_money
	 *
	 * @param accountMoney
	 *                the value for tb_applypaylog.account_money
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public void setAccountMoney(long accountMoney) {
		this.accountMoney = accountMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column tb_applypaylog.record_count
	 *
	 * @return the value of tb_applypaylog.record_count
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public Integer getRecordCount() {
		return recordCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_applypaylog.record_count
	 *
	 * @param recordCount
	 *                the value for tb_applypaylog.record_count
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public void setRecordCount(Integer recordCount) {
		this.recordCount = recordCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column tb_applypaylog.create_time
	 *
	 * @return the value of tb_applypaylog.create_time
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_applypaylog.create_time
	 *
	 * @param createTime
	 *                the value for tb_applypaylog.create_time
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column tb_applypaylog.pay_time
	 *
	 * @return the value of tb_applypaylog.pay_time
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public Date getPayTime() {
		return payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_applypaylog.pay_time
	 *
	 * @param payTime
	 *                the value for tb_applypaylog.pay_time
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column tb_applypaylog.status
	 *
	 * @return the value of tb_applypaylog.status
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_applypaylog.status
	 *
	 * @param status
	 *                the value for tb_applypaylog.status
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column tb_applypaylog.apply_user_id
	 *
	 * @return the value of tb_applypaylog.apply_user_id
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public Long getApplyUserId() {
		return applyUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_applypaylog.apply_user_id
	 *
	 * @param applyUserId
	 *                the value for tb_applypaylog.apply_user_id
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public void setApplyUserId(Long applyUserId) {
		this.applyUserId = applyUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column tb_applypaylog.apply_user_name
	 *
	 * @return the value of tb_applypaylog.apply_user_name
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public String getApplyUserName() {
		return applyUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_applypaylog.apply_user_name
	 *
	 * @param applyUserName
	 *                the value for tb_applypaylog.apply_user_name
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public void setApplyUserName(String applyUserName) {
		this.applyUserName = applyUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column tb_applypaylog.pay_user_id
	 *
	 * @return the value of tb_applypaylog.pay_user_id
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public Long getPayUserId() {
		return payUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_applypaylog.pay_user_id
	 *
	 * @param payUserId
	 *                the value for tb_applypaylog.pay_user_id
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public void setPayUserId(Long payUserId) {
		this.payUserId = payUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column tb_applypaylog.oa_code
	 *
	 * @return the value of tb_applypaylog.oa_code
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public String getOaCode() {
		return oaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_applypaylog.oa_code
	 *
	 * @param oaCode
	 *                the value for tb_applypaylog.oa_code
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public void setOaCode(String oaCode) {
		this.oaCode = oaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns
	 * the value of the database column tb_applypaylog.remark
	 *
	 * @return the value of tb_applypaylog.remark
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_applypaylog.remark
	 *
	 * @param remark
	 *                the value for tb_applypaylog.remark
	 *
	 * @mbggenerated Fri Jul 31 10:40:38 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}