package com.mall.admin.vo.storage;

public class StorageRecordModifylog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_storage_record_modifylog.modify_type_id
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    private Long modifyTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_storage_record_modifylog.storage_record_id
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    private Long storageRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_storage_record_modifylog.seller_id
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    private Long sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_storage_record_modifylog.record_code
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    private String recordCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_storage_record_modifylog.record_type_id
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    private Integer recordTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_storage_record_modifylog.num
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_storage_record_modifylog.price
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_storage_record_modifylog.operator
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    private String operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_storage_record_modifylog.modify_type_id
     *
     * @return the value of tb_storage_record_modifylog.modify_type_id
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public Long getModifyTypeId() {
        return modifyTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_storage_record_modifylog.modify_type_id
     *
     * @param modifyTypeId the value for tb_storage_record_modifylog.modify_type_id
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public void setModifyTypeId(Long modifyTypeId) {
        this.modifyTypeId = modifyTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_storage_record_modifylog.storage_record_id
     *
     * @return the value of tb_storage_record_modifylog.storage_record_id
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public Long getStorageRecordId() {
        return storageRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_storage_record_modifylog.storage_record_id
     *
     * @param storageRecordId the value for tb_storage_record_modifylog.storage_record_id
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public void setStorageRecordId(Long storageRecordId) {
        this.storageRecordId = storageRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_storage_record_modifylog.seller_id
     *
     * @return the value of tb_storage_record_modifylog.seller_id
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_storage_record_modifylog.seller_id
     *
     * @param sellerId the value for tb_storage_record_modifylog.seller_id
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_storage_record_modifylog.record_code
     *
     * @return the value of tb_storage_record_modifylog.record_code
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public String getRecordCode() {
        return recordCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_storage_record_modifylog.record_code
     *
     * @param recordCode the value for tb_storage_record_modifylog.record_code
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public void setRecordCode(String recordCode) {
        this.recordCode = recordCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_storage_record_modifylog.record_type_id
     *
     * @return the value of tb_storage_record_modifylog.record_type_id
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public Integer getRecordTypeId() {
        return recordTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_storage_record_modifylog.record_type_id
     *
     * @param recordTypeId the value for tb_storage_record_modifylog.record_type_id
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public void setRecordTypeId(Integer recordTypeId) {
        this.recordTypeId = recordTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_storage_record_modifylog.num
     *
     * @return the value of tb_storage_record_modifylog.num
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_storage_record_modifylog.num
     *
     * @param num the value for tb_storage_record_modifylog.num
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_storage_record_modifylog.price
     *
     * @return the value of tb_storage_record_modifylog.price
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_storage_record_modifylog.price
     *
     * @param price the value for tb_storage_record_modifylog.price
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_storage_record_modifylog.operator
     *
     * @return the value of tb_storage_record_modifylog.operator
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_storage_record_modifylog.operator
     *
     * @param operator the value for tb_storage_record_modifylog.operator
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }
}