package com.mall.admin.vo.storage;

import java.util.ArrayList;
import java.util.List;

public class StorageRecordModifylogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public StorageRecordModifylogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andModifyTypeIdIsNull() {
            addCriterion("modify_type_id is null");
            return (Criteria) this;
        }

        public Criteria andModifyTypeIdIsNotNull() {
            addCriterion("modify_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTypeIdEqualTo(Long value) {
            addCriterion("modify_type_id =", value, "modifyTypeId");
            return (Criteria) this;
        }

        public Criteria andModifyTypeIdNotEqualTo(Long value) {
            addCriterion("modify_type_id <>", value, "modifyTypeId");
            return (Criteria) this;
        }

        public Criteria andModifyTypeIdGreaterThan(Long value) {
            addCriterion("modify_type_id >", value, "modifyTypeId");
            return (Criteria) this;
        }

        public Criteria andModifyTypeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("modify_type_id >=", value, "modifyTypeId");
            return (Criteria) this;
        }

        public Criteria andModifyTypeIdLessThan(Long value) {
            addCriterion("modify_type_id <", value, "modifyTypeId");
            return (Criteria) this;
        }

        public Criteria andModifyTypeIdLessThanOrEqualTo(Long value) {
            addCriterion("modify_type_id <=", value, "modifyTypeId");
            return (Criteria) this;
        }

        public Criteria andModifyTypeIdIn(List<Long> values) {
            addCriterion("modify_type_id in", values, "modifyTypeId");
            return (Criteria) this;
        }

        public Criteria andModifyTypeIdNotIn(List<Long> values) {
            addCriterion("modify_type_id not in", values, "modifyTypeId");
            return (Criteria) this;
        }

        public Criteria andModifyTypeIdBetween(Long value1, Long value2) {
            addCriterion("modify_type_id between", value1, value2, "modifyTypeId");
            return (Criteria) this;
        }

        public Criteria andModifyTypeIdNotBetween(Long value1, Long value2) {
            addCriterion("modify_type_id not between", value1, value2, "modifyTypeId");
            return (Criteria) this;
        }

        public Criteria andStorageRecordIdIsNull() {
            addCriterion("storage_record_id is null");
            return (Criteria) this;
        }

        public Criteria andStorageRecordIdIsNotNull() {
            addCriterion("storage_record_id is not null");
            return (Criteria) this;
        }

        public Criteria andStorageRecordIdEqualTo(Long value) {
            addCriterion("storage_record_id =", value, "storageRecordId");
            return (Criteria) this;
        }

        public Criteria andStorageRecordIdNotEqualTo(Long value) {
            addCriterion("storage_record_id <>", value, "storageRecordId");
            return (Criteria) this;
        }

        public Criteria andStorageRecordIdGreaterThan(Long value) {
            addCriterion("storage_record_id >", value, "storageRecordId");
            return (Criteria) this;
        }

        public Criteria andStorageRecordIdGreaterThanOrEqualTo(Long value) {
            addCriterion("storage_record_id >=", value, "storageRecordId");
            return (Criteria) this;
        }

        public Criteria andStorageRecordIdLessThan(Long value) {
            addCriterion("storage_record_id <", value, "storageRecordId");
            return (Criteria) this;
        }

        public Criteria andStorageRecordIdLessThanOrEqualTo(Long value) {
            addCriterion("storage_record_id <=", value, "storageRecordId");
            return (Criteria) this;
        }

        public Criteria andStorageRecordIdIn(List<Long> values) {
            addCriterion("storage_record_id in", values, "storageRecordId");
            return (Criteria) this;
        }

        public Criteria andStorageRecordIdNotIn(List<Long> values) {
            addCriterion("storage_record_id not in", values, "storageRecordId");
            return (Criteria) this;
        }

        public Criteria andStorageRecordIdBetween(Long value1, Long value2) {
            addCriterion("storage_record_id between", value1, value2, "storageRecordId");
            return (Criteria) this;
        }

        public Criteria andStorageRecordIdNotBetween(Long value1, Long value2) {
            addCriterion("storage_record_id not between", value1, value2, "storageRecordId");
            return (Criteria) this;
        }

        public Criteria andSellerIdIsNull() {
            addCriterion("seller_id is null");
            return (Criteria) this;
        }

        public Criteria andSellerIdIsNotNull() {
            addCriterion("seller_id is not null");
            return (Criteria) this;
        }

        public Criteria andSellerIdEqualTo(Long value) {
            addCriterion("seller_id =", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotEqualTo(Long value) {
            addCriterion("seller_id <>", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdGreaterThan(Long value) {
            addCriterion("seller_id >", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdGreaterThanOrEqualTo(Long value) {
            addCriterion("seller_id >=", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdLessThan(Long value) {
            addCriterion("seller_id <", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdLessThanOrEqualTo(Long value) {
            addCriterion("seller_id <=", value, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdIn(List<Long> values) {
            addCriterion("seller_id in", values, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotIn(List<Long> values) {
            addCriterion("seller_id not in", values, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdBetween(Long value1, Long value2) {
            addCriterion("seller_id between", value1, value2, "sellerId");
            return (Criteria) this;
        }

        public Criteria andSellerIdNotBetween(Long value1, Long value2) {
            addCriterion("seller_id not between", value1, value2, "sellerId");
            return (Criteria) this;
        }

        public Criteria andRecordCodeIsNull() {
            addCriterion("record_code is null");
            return (Criteria) this;
        }

        public Criteria andRecordCodeIsNotNull() {
            addCriterion("record_code is not null");
            return (Criteria) this;
        }

        public Criteria andRecordCodeEqualTo(String value) {
            addCriterion("record_code =", value, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeNotEqualTo(String value) {
            addCriterion("record_code <>", value, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeGreaterThan(String value) {
            addCriterion("record_code >", value, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeGreaterThanOrEqualTo(String value) {
            addCriterion("record_code >=", value, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeLessThan(String value) {
            addCriterion("record_code <", value, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeLessThanOrEqualTo(String value) {
            addCriterion("record_code <=", value, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeLike(String value) {
            addCriterion("record_code like", value, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeNotLike(String value) {
            addCriterion("record_code not like", value, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeIn(List<String> values) {
            addCriterion("record_code in", values, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeNotIn(List<String> values) {
            addCriterion("record_code not in", values, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeBetween(String value1, String value2) {
            addCriterion("record_code between", value1, value2, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeNotBetween(String value1, String value2) {
            addCriterion("record_code not between", value1, value2, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordTypeIdIsNull() {
            addCriterion("record_type_id is null");
            return (Criteria) this;
        }

        public Criteria andRecordTypeIdIsNotNull() {
            addCriterion("record_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andRecordTypeIdEqualTo(Integer value) {
            addCriterion("record_type_id =", value, "recordTypeId");
            return (Criteria) this;
        }

        public Criteria andRecordTypeIdNotEqualTo(Integer value) {
            addCriterion("record_type_id <>", value, "recordTypeId");
            return (Criteria) this;
        }

        public Criteria andRecordTypeIdGreaterThan(Integer value) {
            addCriterion("record_type_id >", value, "recordTypeId");
            return (Criteria) this;
        }

        public Criteria andRecordTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("record_type_id >=", value, "recordTypeId");
            return (Criteria) this;
        }

        public Criteria andRecordTypeIdLessThan(Integer value) {
            addCriterion("record_type_id <", value, "recordTypeId");
            return (Criteria) this;
        }

        public Criteria andRecordTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("record_type_id <=", value, "recordTypeId");
            return (Criteria) this;
        }

        public Criteria andRecordTypeIdIn(List<Integer> values) {
            addCriterion("record_type_id in", values, "recordTypeId");
            return (Criteria) this;
        }

        public Criteria andRecordTypeIdNotIn(List<Integer> values) {
            addCriterion("record_type_id not in", values, "recordTypeId");
            return (Criteria) this;
        }

        public Criteria andRecordTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("record_type_id between", value1, value2, "recordTypeId");
            return (Criteria) this;
        }

        public Criteria andRecordTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("record_type_id not between", value1, value2, "recordTypeId");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(Integer value) {
            addCriterion("num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(Integer value) {
            addCriterion("num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(Integer value) {
            addCriterion("num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(Integer value) {
            addCriterion("num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(Integer value) {
            addCriterion("num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<Integer> values) {
            addCriterion("num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<Integer> values) {
            addCriterion("num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(Integer value1, Integer value2) {
            addCriterion("num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(Integer value1, Integer value2) {
            addCriterion("num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Integer value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Integer value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Integer value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Integer value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Integer value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Integer> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Integer> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Integer value1, Integer value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("operator is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("operator is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(String value) {
            addCriterion("operator =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(String value) {
            addCriterion("operator <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(String value) {
            addCriterion("operator >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("operator >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(String value) {
            addCriterion("operator <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(String value) {
            addCriterion("operator <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLike(String value) {
            addCriterion("operator like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotLike(String value) {
            addCriterion("operator not like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<String> values) {
            addCriterion("operator in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<String> values) {
            addCriterion("operator not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(String value1, String value2) {
            addCriterion("operator between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(String value1, String value2) {
            addCriterion("operator not between", value1, value2, "operator");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 24 14:11:41 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}