package com.mall.admin.vo.storage;

import com.mall.admin.vo.storage.StorageRecordModifylog;
import com.mall.admin.vo.storage.StorageRecordModifylogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StorageRecordModifylogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    int countByExample(StorageRecordModifylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    int deleteByExample(StorageRecordModifylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    int deleteByPrimaryKey(Long modifyTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    int insert(StorageRecordModifylog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    int insertSelective(StorageRecordModifylog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    List<StorageRecordModifylog> selectByExample(StorageRecordModifylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    StorageRecordModifylog selectByPrimaryKey(Long modifyTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    int updateByExampleSelective(@Param("record") StorageRecordModifylog record, @Param("example") StorageRecordModifylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    int updateByExample(@Param("record") StorageRecordModifylog record, @Param("example") StorageRecordModifylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    int updateByPrimaryKeySelective(StorageRecordModifylog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_storage_record_modifylog
     *
     * @mbggenerated Fri Jul 24 14:11:41 CST 2015
     */
    int updateByPrimaryKey(StorageRecordModifylog record);
}