package com.mall.admin.vo.couponRule;

import com.mall.admin.vo.couponRule.CouponCollege;
import com.mall.admin.vo.couponRule.CouponCollegeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CouponCollegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_college
     *
     * @mbggenerated Tue Jul 21 13:10:51 CST 2015
     */
    int countByExample(CouponCollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_college
     *
     * @mbggenerated Tue Jul 21 13:10:51 CST 2015
     */
    int deleteByExample(CouponCollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_college
     *
     * @mbggenerated Tue Jul 21 13:10:51 CST 2015
     */
    int deleteByPrimaryKey(Integer couponCollegeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_college
     *
     * @mbggenerated Tue Jul 21 13:10:51 CST 2015
     */
    int insert(CouponCollege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_college
     *
     * @mbggenerated Tue Jul 21 13:10:51 CST 2015
     */
    int insertSelective(CouponCollege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_college
     *
     * @mbggenerated Tue Jul 21 13:10:51 CST 2015
     */
    List<CouponCollege> selectByExample(CouponCollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_college
     *
     * @mbggenerated Tue Jul 21 13:10:51 CST 2015
     */
    CouponCollege selectByPrimaryKey(Integer couponCollegeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_college
     *
     * @mbggenerated Tue Jul 21 13:10:51 CST 2015
     */
    int updateByExampleSelective(@Param("record") CouponCollege record, @Param("example") CouponCollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_college
     *
     * @mbggenerated Tue Jul 21 13:10:51 CST 2015
     */
    int updateByExample(@Param("record") CouponCollege record, @Param("example") CouponCollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_college
     *
     * @mbggenerated Tue Jul 21 13:10:51 CST 2015
     */
    int updateByPrimaryKeySelective(CouponCollege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_coupon_college
     *
     * @mbggenerated Tue Jul 21 13:10:51 CST 2015
     */
    int updateByPrimaryKey(CouponCollege record);
}