package com.mall.admin.vo.couponRule;

import java.util.Date;

public class CouponRule {
	
    // 首单减
	public static final long FIRST_ORDER_COUPON = 1L;
	// 满减
    public static final long SELLER_COUPON = 2L;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupon_rule.coupon_id
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    private Integer couponId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupon_rule.coupon_name
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    private String couponName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupon_rule.description
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupon_rule.coupon_type
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    private Byte couponType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupon_rule.total_money
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    private Integer totalMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupon_rule.sub_money
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    private Integer subMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupon_rule.create_time
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupon_rule.update_time
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupon_rule.operator
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    private Integer operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupon_rule.begin_time
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupon_rule.end_time
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupon_rule.is_del
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    private Byte isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupon_rule.coupon_id
     *
     * @return the value of tb_coupon_rule.coupon_id
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupon_rule.coupon_id
     *
     * @param couponId the value for tb_coupon_rule.coupon_id
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupon_rule.coupon_name
     *
     * @return the value of tb_coupon_rule.coupon_name
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public String getCouponName() {
        return couponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupon_rule.coupon_name
     *
     * @param couponName the value for tb_coupon_rule.coupon_name
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public void setCouponName(String couponName) {
        this.couponName = couponName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupon_rule.description
     *
     * @return the value of tb_coupon_rule.description
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupon_rule.description
     *
     * @param description the value for tb_coupon_rule.description
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupon_rule.coupon_type
     *
     * @return the value of tb_coupon_rule.coupon_type
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public Byte getCouponType() {
        return couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupon_rule.coupon_type
     *
     * @param couponType the value for tb_coupon_rule.coupon_type
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public void setCouponType(Byte couponType) {
        this.couponType = couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupon_rule.total_money
     *
     * @return the value of tb_coupon_rule.total_money
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public Integer getTotalMoney() {
        return totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupon_rule.total_money
     *
     * @param totalMoney the value for tb_coupon_rule.total_money
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public void setTotalMoney(Integer totalMoney) {
        this.totalMoney = totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupon_rule.sub_money
     *
     * @return the value of tb_coupon_rule.sub_money
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public Integer getSubMoney() {
        return subMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupon_rule.sub_money
     *
     * @param subMoney the value for tb_coupon_rule.sub_money
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public void setSubMoney(Integer subMoney) {
        this.subMoney = subMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupon_rule.create_time
     *
     * @return the value of tb_coupon_rule.create_time
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupon_rule.create_time
     *
     * @param createTime the value for tb_coupon_rule.create_time
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupon_rule.update_time
     *
     * @return the value of tb_coupon_rule.update_time
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupon_rule.update_time
     *
     * @param updateTime the value for tb_coupon_rule.update_time
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupon_rule.operator
     *
     * @return the value of tb_coupon_rule.operator
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public Integer getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupon_rule.operator
     *
     * @param operator the value for tb_coupon_rule.operator
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public void setOperator(Integer operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupon_rule.begin_time
     *
     * @return the value of tb_coupon_rule.begin_time
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupon_rule.begin_time
     *
     * @param beginTime the value for tb_coupon_rule.begin_time
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupon_rule.end_time
     *
     * @return the value of tb_coupon_rule.end_time
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupon_rule.end_time
     *
     * @param endTime the value for tb_coupon_rule.end_time
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupon_rule.is_del
     *
     * @return the value of tb_coupon_rule.is_del
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public Byte getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupon_rule.is_del
     *
     * @param isDel the value for tb_coupon_rule.is_del
     *
     * @mbggenerated Mon Jul 20 10:28:13 CST 2015
     */
    public void setIsDel(Byte isDel) {
        this.isDel = isDel;
    }
}