package com.mall.admin.vo.couponRule;

import java.util.Date;

import com.mall.admin.util._;

public class CouponRegion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupon_region.coupon_region_id
     *
     * @mbggenerated Tue Jul 21 17:45:30 CST 2015
     */
    private Integer couponRegionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupon_region.coupon_rule_id
     *
     * @mbggenerated Tue Jul 21 17:45:30 CST 2015
     */
    private Integer couponRuleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupon_region.city_id
     *
     * @mbggenerated Tue Jul 21 17:45:30 CST 2015
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupon_region.is_del
     *
     * @mbggenerated Tue Jul 21 17:45:30 CST 2015
     */
    private Byte isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupon_region.create_time
     *
     * @mbggenerated Tue Jul 21 17:45:30 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupon_region.update_time
     *
     * @mbggenerated Tue Jul 21 17:45:30 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_coupon_region.operator
     *
     * @mbggenerated Tue Jul 21 17:45:30 CST 2015
     */
    private Integer operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupon_region.coupon_region_id
     *
     * @return the value of tb_coupon_region.coupon_region_id
     *
     * @mbggenerated Tue Jul 21 17:45:30 CST 2015
     */
    public Integer getCouponRegionId() {
        return couponRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupon_region.coupon_region_id
     *
     * @param couponRegionId the value for tb_coupon_region.coupon_region_id
     *
     * @mbggenerated Tue Jul 21 17:45:30 CST 2015
     */
    public void setCouponRegionId(Integer couponRegionId) {
        this.couponRegionId = couponRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupon_region.coupon_rule_id
     *
     * @return the value of tb_coupon_region.coupon_rule_id
     *
     * @mbggenerated Tue Jul 21 17:45:30 CST 2015
     */
    public Integer getCouponRuleId() {
        return couponRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupon_region.coupon_rule_id
     *
     * @param couponRuleId the value for tb_coupon_region.coupon_rule_id
     *
     * @mbggenerated Tue Jul 21 17:45:30 CST 2015
     */
    public void setCouponRuleId(Integer couponRuleId) {
        this.couponRuleId = couponRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupon_region.city_id
     *
     * @return the value of tb_coupon_region.city_id
     *
     * @mbggenerated Tue Jul 21 17:45:30 CST 2015
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupon_region.city_id
     *
     * @param cityId the value for tb_coupon_region.city_id
     *
     * @mbggenerated Tue Jul 21 17:45:30 CST 2015
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupon_region.is_del
     *
     * @return the value of tb_coupon_region.is_del
     *
     * @mbggenerated Tue Jul 21 17:45:30 CST 2015
     */
    public Byte getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupon_region.is_del
     *
     * @param isDel the value for tb_coupon_region.is_del
     *
     * @mbggenerated Tue Jul 21 17:45:30 CST 2015
     */
    public void setIsDel(Byte isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupon_region.create_time
     *
     * @return the value of tb_coupon_region.create_time
     *
     * @mbggenerated Tue Jul 21 17:45:30 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupon_region.create_time
     *
     * @param createTime the value for tb_coupon_region.create_time
     *
     * @mbggenerated Tue Jul 21 17:45:30 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupon_region.update_time
     *
     * @return the value of tb_coupon_region.update_time
     *
     * @mbggenerated Tue Jul 21 17:45:30 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupon_region.update_time
     *
     * @param updateTime the value for tb_coupon_region.update_time
     *
     * @mbggenerated Tue Jul 21 17:45:30 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_coupon_region.operator
     *
     * @return the value of tb_coupon_region.operator
     *
     * @mbggenerated Tue Jul 21 17:45:30 CST 2015
     */
    public Integer getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_coupon_region.operator
     *
     * @param operator the value for tb_coupon_region.operator
     *
     * @mbggenerated Tue Jul 21 17:45:30 CST 2015
     */
    public void setOperator(Integer operator) {
        this.operator = operator;
    }
    
    public static CouponRegion getBean() {
    	Date now = new Date();
    	CouponRegion couponRegion = new CouponRegion();
    	couponRegion.setIsDel(_.toByte(0));
    	couponRegion.setCreateTime(now);
    	couponRegion.setUpdateTime(now);
    	return couponRegion;
    }
    
}