package com.mall.admin.vo.mallbase;

import com.mall.admin.vo.mallbase.College;
import com.mall.admin.vo.mallbase.CollegeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    int countByExample(CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    int deleteByExample(CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    int deleteByPrimaryKey(Long collegeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    int insert(College record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    int insertSelective(College record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    List<College> selectByExample(CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    College selectByPrimaryKey(Long collegeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    int updateByExampleSelective(@Param("record") College record, @Param("example") CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    int updateByExample(@Param("record") College record, @Param("example") CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    int updateByPrimaryKeySelective(College record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    int updateByPrimaryKey(College record);
}