package com.mall.admin.vo.mallbase;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CollegeExample {
	
	protected int start;
	protected int limit;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    public CollegeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCollegeIdIsNull() {
            addCriterion("college_id is null");
            return (Criteria) this;
        }

        public Criteria andCollegeIdIsNotNull() {
            addCriterion("college_id is not null");
            return (Criteria) this;
        }

        public Criteria andCollegeIdEqualTo(Long value) {
            addCriterion("college_id =", value, "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeIdNotEqualTo(Long value) {
            addCriterion("college_id <>", value, "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeIdGreaterThan(Long value) {
            addCriterion("college_id >", value, "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("college_id >=", value, "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeIdLessThan(Long value) {
            addCriterion("college_id <", value, "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeIdLessThanOrEqualTo(Long value) {
            addCriterion("college_id <=", value, "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeIdIn(List<Long> values) {
            addCriterion("college_id in", values, "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeIdNotIn(List<Long> values) {
            addCriterion("college_id not in", values, "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeIdBetween(Long value1, Long value2) {
            addCriterion("college_id between", value1, value2, "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeIdNotBetween(Long value1, Long value2) {
            addCriterion("college_id not between", value1, value2, "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeNameIsNull() {
            addCriterion("college_name is null");
            return (Criteria) this;
        }

        public Criteria andCollegeNameIsNotNull() {
            addCriterion("college_name is not null");
            return (Criteria) this;
        }

        public Criteria andCollegeNameEqualTo(String value) {
            addCriterion("college_name =", value, "collegeName");
            return (Criteria) this;
        }

        public Criteria andCollegeNameNotEqualTo(String value) {
            addCriterion("college_name <>", value, "collegeName");
            return (Criteria) this;
        }

        public Criteria andCollegeNameGreaterThan(String value) {
            addCriterion("college_name >", value, "collegeName");
            return (Criteria) this;
        }

        public Criteria andCollegeNameGreaterThanOrEqualTo(String value) {
            addCriterion("college_name >=", value, "collegeName");
            return (Criteria) this;
        }

        public Criteria andCollegeNameLessThan(String value) {
            addCriterion("college_name <", value, "collegeName");
            return (Criteria) this;
        }

        public Criteria andCollegeNameLessThanOrEqualTo(String value) {
            addCriterion("college_name <=", value, "collegeName");
            return (Criteria) this;
        }

        public Criteria andCollegeNameLike(String value) {
            addCriterion("college_name like", value, "collegeName");
            return (Criteria) this;
        }

        public Criteria andCollegeNameNotLike(String value) {
            addCriterion("college_name not like", value, "collegeName");
            return (Criteria) this;
        }

        public Criteria andCollegeIdLike(String value) {
            addCriterion("college_id like", "%"+value+"%", "collegeId");
            return (Criteria) this;
        }

        public Criteria andCollegeIdNotLike(String value) {
            addCriterion("college_id not like", "%"+value+"%", "collegeId");
            return (Criteria) this;
        }
        
        public Criteria andCollegeNameIn(List<String> values) {
            addCriterion("college_name in", values, "collegeName");
            return (Criteria) this;
        }

        public Criteria andCollegeNameNotIn(List<String> values) {
            addCriterion("college_name not in", values, "collegeName");
            return (Criteria) this;
        }

        public Criteria andCollegeNameBetween(String value1, String value2) {
            addCriterion("college_name between", value1, value2, "collegeName");
            return (Criteria) this;
        }

        public Criteria andCollegeNameNotBetween(String value1, String value2) {
            addCriterion("college_name not between", value1, value2, "collegeName");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNull() {
            addCriterion("city_id is null");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNotNull() {
            addCriterion("city_id is not null");
            return (Criteria) this;
        }

        public Criteria andCityIdEqualTo(Long value) {
            addCriterion("city_id =", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotEqualTo(Long value) {
            addCriterion("city_id <>", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThan(Long value) {
            addCriterion("city_id >", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThanOrEqualTo(Long value) {
            addCriterion("city_id >=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThan(Long value) {
            addCriterion("city_id <", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThanOrEqualTo(Long value) {
            addCriterion("city_id <=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdIn(List<Long> values) {
            addCriterion("city_id in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotIn(List<Long> values) {
            addCriterion("city_id not in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdBetween(Long value1, Long value2) {
            addCriterion("city_id between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotBetween(Long value1, Long value2) {
            addCriterion("city_id not between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andRdcStorageIdIsNull() {
            addCriterion("rdc_storage_id is null");
            return (Criteria) this;
        }

        public Criteria andRdcStorageIdIsNotNull() {
            addCriterion("rdc_storage_id is not null");
            return (Criteria) this;
        }

        public Criteria andRdcStorageIdEqualTo(Long value) {
            addCriterion("rdc_storage_id =", value, "rdcStorageId");
            return (Criteria) this;
        }

        public Criteria andRdcStorageIdNotEqualTo(Long value) {
            addCriterion("rdc_storage_id <>", value, "rdcStorageId");
            return (Criteria) this;
        }

        public Criteria andRdcStorageIdGreaterThan(Long value) {
            addCriterion("rdc_storage_id >", value, "rdcStorageId");
            return (Criteria) this;
        }

        public Criteria andRdcStorageIdGreaterThanOrEqualTo(Long value) {
            addCriterion("rdc_storage_id >=", value, "rdcStorageId");
            return (Criteria) this;
        }

        public Criteria andRdcStorageIdLessThan(Long value) {
            addCriterion("rdc_storage_id <", value, "rdcStorageId");
            return (Criteria) this;
        }

        public Criteria andRdcStorageIdLessThanOrEqualTo(Long value) {
            addCriterion("rdc_storage_id <=", value, "rdcStorageId");
            return (Criteria) this;
        }

        public Criteria andRdcStorageIdIn(List<Long> values) {
            addCriterion("rdc_storage_id in", values, "rdcStorageId");
            return (Criteria) this;
        }

        public Criteria andRdcStorageIdNotIn(List<Long> values) {
            addCriterion("rdc_storage_id not in", values, "rdcStorageId");
            return (Criteria) this;
        }

        public Criteria andRdcStorageIdBetween(Long value1, Long value2) {
            addCriterion("rdc_storage_id between", value1, value2, "rdcStorageId");
            return (Criteria) this;
        }

        public Criteria andRdcStorageIdNotBetween(Long value1, Long value2) {
            addCriterion("rdc_storage_id not between", value1, value2, "rdcStorageId");
            return (Criteria) this;
        }

        public Criteria andLdcStorageIdIsNull() {
            addCriterion("ldc_storage_id is null");
            return (Criteria) this;
        }

        public Criteria andLdcStorageIdIsNotNull() {
            addCriterion("ldc_storage_id is not null");
            return (Criteria) this;
        }

        public Criteria andLdcStorageIdEqualTo(Long value) {
            addCriterion("ldc_storage_id =", value, "ldcStorageId");
            return (Criteria) this;
        }

        public Criteria andLdcStorageIdNotEqualTo(Long value) {
            addCriterion("ldc_storage_id <>", value, "ldcStorageId");
            return (Criteria) this;
        }

        public Criteria andLdcStorageIdGreaterThan(Long value) {
            addCriterion("ldc_storage_id >", value, "ldcStorageId");
            return (Criteria) this;
        }

        public Criteria andLdcStorageIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ldc_storage_id >=", value, "ldcStorageId");
            return (Criteria) this;
        }

        public Criteria andLdcStorageIdLessThan(Long value) {
            addCriterion("ldc_storage_id <", value, "ldcStorageId");
            return (Criteria) this;
        }

        public Criteria andLdcStorageIdLessThanOrEqualTo(Long value) {
            addCriterion("ldc_storage_id <=", value, "ldcStorageId");
            return (Criteria) this;
        }

        public Criteria andLdcStorageIdIn(List<Long> values) {
            addCriterion("ldc_storage_id in", values, "ldcStorageId");
            return (Criteria) this;
        }

        public Criteria andLdcStorageIdNotIn(List<Long> values) {
            addCriterion("ldc_storage_id not in", values, "ldcStorageId");
            return (Criteria) this;
        }

        public Criteria andLdcStorageIdBetween(Long value1, Long value2) {
            addCriterion("ldc_storage_id between", value1, value2, "ldcStorageId");
            return (Criteria) this;
        }

        public Criteria andLdcStorageIdNotBetween(Long value1, Long value2) {
            addCriterion("ldc_storage_id not between", value1, value2, "ldcStorageId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("operator is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("operator is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(Long value) {
            addCriterion("operator =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(Long value) {
            addCriterion("operator <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(Long value) {
            addCriterion("operator >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(Long value) {
            addCriterion("operator >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(Long value) {
            addCriterion("operator <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(Long value) {
            addCriterion("operator <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<Long> values) {
            addCriterion("operator in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<Long> values) {
            addCriterion("operator not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(Long value1, Long value2) {
            addCriterion("operator between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(Long value1, Long value2) {
            addCriterion("operator not between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("is_del is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("is_del is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(Byte value) {
            addCriterion("is_del =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(Byte value) {
            addCriterion("is_del <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(Byte value) {
            addCriterion("is_del >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_del >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(Byte value) {
            addCriterion("is_del <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(Byte value) {
            addCriterion("is_del <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<Byte> values) {
            addCriterion("is_del in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<Byte> values) {
            addCriterion("is_del not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(Byte value1, Byte value2) {
            addCriterion("is_del between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(Byte value1, Byte value2) {
            addCriterion("is_del not between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsOpenIsNull() {
            addCriterion("is_open is null");
            return (Criteria) this;
        }

        public Criteria andIsOpenIsNotNull() {
            addCriterion("is_open is not null");
            return (Criteria) this;
        }

        public Criteria andIsOpenEqualTo(Byte value) {
            addCriterion("is_open =", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenNotEqualTo(Byte value) {
            addCriterion("is_open <>", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenGreaterThan(Byte value) {
            addCriterion("is_open >", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_open >=", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenLessThan(Byte value) {
            addCriterion("is_open <", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenLessThanOrEqualTo(Byte value) {
            addCriterion("is_open <=", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenIn(List<Byte> values) {
            addCriterion("is_open in", values, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenNotIn(List<Byte> values) {
            addCriterion("is_open not in", values, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenBetween(Byte value1, Byte value2) {
            addCriterion("is_open between", value1, value2, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenNotBetween(Byte value1, Byte value2) {
            addCriterion("is_open not between", value1, value2, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsShowIsNull() {
            addCriterion("is_show is null");
            return (Criteria) this;
        }

        public Criteria andIsShowIsNotNull() {
            addCriterion("is_show is not null");
            return (Criteria) this;
        }

        public Criteria andIsShowEqualTo(Byte value) {
            addCriterion("is_show =", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowNotEqualTo(Byte value) {
            addCriterion("is_show <>", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowGreaterThan(Byte value) {
            addCriterion("is_show >", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_show >=", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowLessThan(Byte value) {
            addCriterion("is_show <", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowLessThanOrEqualTo(Byte value) {
            addCriterion("is_show <=", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowIn(List<Byte> values) {
            addCriterion("is_show in", values, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowNotIn(List<Byte> values) {
            addCriterion("is_show not in", values, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowBetween(Byte value1, Byte value2) {
            addCriterion("is_show between", value1, value2, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowNotBetween(Byte value1, Byte value2) {
            addCriterion("is_show not between", value1, value2, "isShow");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("latitude is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("latitude is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(BigDecimal value) {
            addCriterion("latitude =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(BigDecimal value) {
            addCriterion("latitude <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(BigDecimal value) {
            addCriterion("latitude >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("latitude >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(BigDecimal value) {
            addCriterion("latitude <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("latitude <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<BigDecimal> values) {
            addCriterion("latitude in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<BigDecimal> values) {
            addCriterion("latitude not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("latitude between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("latitude not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("longitude is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("longitude is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(BigDecimal value) {
            addCriterion("longitude =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(BigDecimal value) {
            addCriterion("longitude <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(BigDecimal value) {
            addCriterion("longitude >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("longitude >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(BigDecimal value) {
            addCriterion("longitude <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("longitude <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<BigDecimal> values) {
            addCriterion("longitude in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<BigDecimal> values) {
            addCriterion("longitude not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("longitude between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("longitude not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNull() {
            addCriterion("area_id is null");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNotNull() {
            addCriterion("area_id is not null");
            return (Criteria) this;
        }

        public Criteria andAreaIdEqualTo(Long value) {
            addCriterion("area_id =", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotEqualTo(Long value) {
            addCriterion("area_id <>", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThan(Long value) {
            addCriterion("area_id >", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThanOrEqualTo(Long value) {
            addCriterion("area_id >=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThan(Long value) {
            addCriterion("area_id <", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThanOrEqualTo(Long value) {
            addCriterion("area_id <=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIn(List<Long> values) {
            addCriterion("area_id in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotIn(List<Long> values) {
            addCriterion("area_id not in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdBetween(Long value1, Long value2) {
            addCriterion("area_id between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotBetween(Long value1, Long value2) {
            addCriterion("area_id not between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryTypeIsNull() {
            addCriterion("ldc_delivery_type is null");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryTypeIsNotNull() {
            addCriterion("ldc_delivery_type is not null");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryTypeEqualTo(Byte value) {
            addCriterion("ldc_delivery_type =", value, "ldcDeliveryType");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryTypeNotEqualTo(Byte value) {
            addCriterion("ldc_delivery_type <>", value, "ldcDeliveryType");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryTypeGreaterThan(Byte value) {
            addCriterion("ldc_delivery_type >", value, "ldcDeliveryType");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("ldc_delivery_type >=", value, "ldcDeliveryType");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryTypeLessThan(Byte value) {
            addCriterion("ldc_delivery_type <", value, "ldcDeliveryType");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryTypeLessThanOrEqualTo(Byte value) {
            addCriterion("ldc_delivery_type <=", value, "ldcDeliveryType");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryTypeIn(List<Byte> values) {
            addCriterion("ldc_delivery_type in", values, "ldcDeliveryType");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryTypeNotIn(List<Byte> values) {
            addCriterion("ldc_delivery_type not in", values, "ldcDeliveryType");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryTypeBetween(Byte value1, Byte value2) {
            addCriterion("ldc_delivery_type between", value1, value2, "ldcDeliveryType");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("ldc_delivery_type not between", value1, value2, "ldcDeliveryType");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryAddressIsNull() {
            addCriterion("ldc_delivery_address is null");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryAddressIsNotNull() {
            addCriterion("ldc_delivery_address is not null");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryAddressEqualTo(String value) {
            addCriterion("ldc_delivery_address =", value, "ldcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryAddressNotEqualTo(String value) {
            addCriterion("ldc_delivery_address <>", value, "ldcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryAddressGreaterThan(String value) {
            addCriterion("ldc_delivery_address >", value, "ldcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ldc_delivery_address >=", value, "ldcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryAddressLessThan(String value) {
            addCriterion("ldc_delivery_address <", value, "ldcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryAddressLessThanOrEqualTo(String value) {
            addCriterion("ldc_delivery_address <=", value, "ldcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryAddressLike(String value) {
            addCriterion("ldc_delivery_address like", value, "ldcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryAddressNotLike(String value) {
            addCriterion("ldc_delivery_address not like", value, "ldcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryAddressIn(List<String> values) {
            addCriterion("ldc_delivery_address in", values, "ldcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryAddressNotIn(List<String> values) {
            addCriterion("ldc_delivery_address not in", values, "ldcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryAddressBetween(String value1, String value2) {
            addCriterion("ldc_delivery_address between", value1, value2, "ldcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andLdcDeliveryAddressNotBetween(String value1, String value2) {
            addCriterion("ldc_delivery_address not between", value1, value2, "ldcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryTypeIsNull() {
            addCriterion("rdc_delivery_type is null");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryTypeIsNotNull() {
            addCriterion("rdc_delivery_type is not null");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryTypeEqualTo(Byte value) {
            addCriterion("rdc_delivery_type =", value, "rdcDeliveryType");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryTypeNotEqualTo(Byte value) {
            addCriterion("rdc_delivery_type <>", value, "rdcDeliveryType");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryTypeGreaterThan(Byte value) {
            addCriterion("rdc_delivery_type >", value, "rdcDeliveryType");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("rdc_delivery_type >=", value, "rdcDeliveryType");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryTypeLessThan(Byte value) {
            addCriterion("rdc_delivery_type <", value, "rdcDeliveryType");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryTypeLessThanOrEqualTo(Byte value) {
            addCriterion("rdc_delivery_type <=", value, "rdcDeliveryType");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryTypeIn(List<Byte> values) {
            addCriterion("rdc_delivery_type in", values, "rdcDeliveryType");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryTypeNotIn(List<Byte> values) {
            addCriterion("rdc_delivery_type not in", values, "rdcDeliveryType");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryTypeBetween(Byte value1, Byte value2) {
            addCriterion("rdc_delivery_type between", value1, value2, "rdcDeliveryType");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("rdc_delivery_type not between", value1, value2, "rdcDeliveryType");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryAddressIsNull() {
            addCriterion("rdc_delivery_address is null");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryAddressIsNotNull() {
            addCriterion("rdc_delivery_address is not null");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryAddressEqualTo(String value) {
            addCriterion("rdc_delivery_address =", value, "rdcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryAddressNotEqualTo(String value) {
            addCriterion("rdc_delivery_address <>", value, "rdcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryAddressGreaterThan(String value) {
            addCriterion("rdc_delivery_address >", value, "rdcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryAddressGreaterThanOrEqualTo(String value) {
            addCriterion("rdc_delivery_address >=", value, "rdcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryAddressLessThan(String value) {
            addCriterion("rdc_delivery_address <", value, "rdcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryAddressLessThanOrEqualTo(String value) {
            addCriterion("rdc_delivery_address <=", value, "rdcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryAddressLike(String value) {
            addCriterion("rdc_delivery_address like", value, "rdcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryAddressNotLike(String value) {
            addCriterion("rdc_delivery_address not like", value, "rdcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryAddressIn(List<String> values) {
            addCriterion("rdc_delivery_address in", values, "rdcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryAddressNotIn(List<String> values) {
            addCriterion("rdc_delivery_address not in", values, "rdcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryAddressBetween(String value1, String value2) {
            addCriterion("rdc_delivery_address between", value1, value2, "rdcDeliveryAddress");
            return (Criteria) this;
        }

        public Criteria andRdcDeliveryAddressNotBetween(String value1, String value2) {
            addCriterion("rdc_delivery_address not between", value1, value2, "rdcDeliveryAddress");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_college
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 04 10:01:04 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_college
     *
     * @mbggenerated Tue Aug 04 10:01:04 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

	public int getStart() {
		return start;
	}

	public CollegeExample setStart(int start) {
		this.start = start;
		return this;
	}

	public int getLimit() {
		return limit;
	}

	public CollegeExample setLimit(int limit) {
		this.limit = limit;
		return this;
	}
}