package com.mall.admin.vo.activity;

import java.util.Date;

import com.mall.admin.util._;
import com.mall.admin.vo.couponRule.CouponCollege;

public class ActivityCollege {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_college.activity_college_id
     *
     * @mbggenerated Sat Jul 25 10:00:33 CST 2015
     */
    private Long activityCollegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_college.activity_id
     *
     * @mbggenerated Sat Jul 25 10:00:33 CST 2015
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_college.college_id
     *
     * @mbggenerated Sat Jul 25 10:00:33 CST 2015
     */
    private Long collegeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_college.is_del
     *
     * @mbggenerated Sat Jul 25 10:00:33 CST 2015
     */
    private Byte isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_college.create_time
     *
     * @mbggenerated Sat Jul 25 10:00:33 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_college.update_time
     *
     * @mbggenerated Sat Jul 25 10:00:33 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_college.operator
     *
     * @mbggenerated Sat Jul 25 10:00:33 CST 2015
     */
    private Integer operator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_college.activity_college_id
     *
     * @return the value of tb_activity_college.activity_college_id
     *
     * @mbggenerated Sat Jul 25 10:00:33 CST 2015
     */
    public Long getActivityCollegeId() {
        return activityCollegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_college.activity_college_id
     *
     * @param activityCollegeId the value for tb_activity_college.activity_college_id
     *
     * @mbggenerated Sat Jul 25 10:00:33 CST 2015
     */
    public void setActivityCollegeId(Long activityCollegeId) {
        this.activityCollegeId = activityCollegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_college.activity_id
     *
     * @return the value of tb_activity_college.activity_id
     *
     * @mbggenerated Sat Jul 25 10:00:33 CST 2015
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_college.activity_id
     *
     * @param activityId the value for tb_activity_college.activity_id
     *
     * @mbggenerated Sat Jul 25 10:00:33 CST 2015
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_college.college_id
     *
     * @return the value of tb_activity_college.college_id
     *
     * @mbggenerated Sat Jul 25 10:00:33 CST 2015
     */
    public Long getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_college.college_id
     *
     * @param collegeId the value for tb_activity_college.college_id
     *
     * @mbggenerated Sat Jul 25 10:00:33 CST 2015
     */
    public void setCollegeId(Long collegeId) {
        this.collegeId = collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_college.is_del
     *
     * @return the value of tb_activity_college.is_del
     *
     * @mbggenerated Sat Jul 25 10:00:33 CST 2015
     */
    public Byte getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_college.is_del
     *
     * @param isDel the value for tb_activity_college.is_del
     *
     * @mbggenerated Sat Jul 25 10:00:33 CST 2015
     */
    public void setIsDel(Byte isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_college.create_time
     *
     * @return the value of tb_activity_college.create_time
     *
     * @mbggenerated Sat Jul 25 10:00:33 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_college.create_time
     *
     * @param createTime the value for tb_activity_college.create_time
     *
     * @mbggenerated Sat Jul 25 10:00:33 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_college.update_time
     *
     * @return the value of tb_activity_college.update_time
     *
     * @mbggenerated Sat Jul 25 10:00:33 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_college.update_time
     *
     * @param updateTime the value for tb_activity_college.update_time
     *
     * @mbggenerated Sat Jul 25 10:00:33 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_college.operator
     *
     * @return the value of tb_activity_college.operator
     *
     * @mbggenerated Sat Jul 25 10:00:33 CST 2015
     */
    public Integer getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_college.operator
     *
     * @param operator the value for tb_activity_college.operator
     *
     * @mbggenerated Sat Jul 25 10:00:33 CST 2015
     */
    public void setOperator(Integer operator) {
        this.operator = operator;
    }
    
    public static ActivityCollege getBean() {
    	Date now = new Date();
    	ActivityCollege activityCollege = new ActivityCollege();
    	activityCollege.setIsDel(_.toByte(0));
    	activityCollege.setCreateTime(now);
    	activityCollege.setUpdateTime(now);
    	return activityCollege;
    }
}