package com.mall.admin.vo.activity;

import com.mall.admin.vo.activity.ActivityTime;
import com.mall.admin.vo.activity.ActivityTimeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    int countByExample(ActivityTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    int deleteByExample(ActivityTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    int deleteByPrimaryKey(Long activityTimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    int insert(ActivityTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    int insertSelective(ActivityTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    List<ActivityTime> selectByExample(ActivityTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    ActivityTime selectByPrimaryKey(Long activityTimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    int updateByExampleSelective(@Param("record") ActivityTime record, @Param("example") ActivityTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    int updateByExample(@Param("record") ActivityTime record, @Param("example") ActivityTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    int updateByPrimaryKeySelective(ActivityTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    int updateByPrimaryKey(ActivityTime record);
}