package com.mall.admin.vo.activity;

import java.util.Date;

public class ActivityTime {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_time.activity_time_id
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    private Long activityTimeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_time.activity_id
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_time.begin_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_time.end_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_time.create_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_time.update_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_time.isdel
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    private Byte isdel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_time.activity_time_id
     *
     * @return the value of tb_activity_time.activity_time_id
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    public Long getActivityTimeId() {
        return activityTimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_time.activity_time_id
     *
     * @param activityTimeId the value for tb_activity_time.activity_time_id
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    public void setActivityTimeId(Long activityTimeId) {
        this.activityTimeId = activityTimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_time.activity_id
     *
     * @return the value of tb_activity_time.activity_id
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_time.activity_id
     *
     * @param activityId the value for tb_activity_time.activity_id
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_time.begin_time
     *
     * @return the value of tb_activity_time.begin_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_time.begin_time
     *
     * @param beginTime the value for tb_activity_time.begin_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_time.end_time
     *
     * @return the value of tb_activity_time.end_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_time.end_time
     *
     * @param endTime the value for tb_activity_time.end_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_time.create_time
     *
     * @return the value of tb_activity_time.create_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_time.create_time
     *
     * @param createTime the value for tb_activity_time.create_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_time.update_time
     *
     * @return the value of tb_activity_time.update_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_time.update_time
     *
     * @param updateTime the value for tb_activity_time.update_time
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_time.isdel
     *
     * @return the value of tb_activity_time.isdel
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    public Byte getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_time.isdel
     *
     * @param isdel the value for tb_activity_time.isdel
     *
     * @mbggenerated Sat Jul 25 15:17:57 CST 2015
     */
    public void setIsdel(Byte isdel) {
        this.isdel = isdel;
    }
}