package com.mall.admin.vo.subscribe;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

public class SubscribeDetail implements Serializable{

	/**
	 * 广告平台
	 */
	public final static int SUBSCRIBE_ADVERTISE_PLATFORM_TYPE = 1;
	
	/**
	 * 活动、信息平台
	 */
	public final static int SUBSCRIBE_ACTIVITY_PLATFORM_TYPE = 0;
	
	/**
	 * 活动内容类型
	 */
	public final static int SUBSCRIBE_ACTIVITY_CONTENT_TYPE = 0;
	
	/**
	 * 信息内容类型
	 */
	public final static int SUBSCRIBE_INFO_CONTENT_TYPE = 1;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_subscribe_detail.subscribe_id
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	private Long subscribeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_subscribe_detail.title
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_subscribe_detail.sub_title
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	private String subTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_subscribe_detail.html_url
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	private String htmlUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_subscribe_detail.img_url
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	private String imgUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_subscribe_detail.platform_type
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	private Integer platformType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_subscribe_detail.content_type
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	private Integer contentType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_subscribe_detail.status
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_subscribe_detail.weight
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	private Integer weight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_subscribe_detail.operator
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	private Long operator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_subscribe_detail.create_time
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_subscribe_detail.update_time
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	private Date updateTime;
	
	
	/**
	 * 查询条件--标题或链接
	 */
	private String titleOrHtmlUrl;
	
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_subscribe_detail.subscribe_id
	 * @return  the value of tb_subscribe_detail.subscribe_id
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public Long getSubscribeId() {
		return subscribeId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_subscribe_detail.subscribe_id
	 * @param subscribeId  the value for tb_subscribe_detail.subscribe_id
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public void setSubscribeId(Long subscribeId) {
		this.subscribeId = subscribeId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_subscribe_detail.title
	 * @return  the value of tb_subscribe_detail.title
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public String getTitle() {
		return title;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_subscribe_detail.title
	 * @param title  the value for tb_subscribe_detail.title
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public void setTitle(String title) {
		this.title = title;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_subscribe_detail.sub_title
	 * @return  the value of tb_subscribe_detail.sub_title
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public String getSubTitle() {
		return subTitle;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_subscribe_detail.sub_title
	 * @param subTitle  the value for tb_subscribe_detail.sub_title
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public void setSubTitle(String subTitle) {
		this.subTitle = subTitle;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_subscribe_detail.html_url
	 * @return  the value of tb_subscribe_detail.html_url
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public String getHtmlUrl() {
		return htmlUrl;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_subscribe_detail.html_url
	 * @param htmlUrl  the value for tb_subscribe_detail.html_url
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public void setHtmlUrl(String htmlUrl) {
		this.htmlUrl = htmlUrl;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_subscribe_detail.img_url
	 * @return  the value of tb_subscribe_detail.img_url
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public String getImgUrl() {
		return imgUrl;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_subscribe_detail.img_url
	 * @param imgUrl  the value for tb_subscribe_detail.img_url
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_subscribe_detail.platform_type
	 * @return  the value of tb_subscribe_detail.platform_type
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public Integer getPlatformType() {
		return platformType;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_subscribe_detail.platform_type
	 * @param platformType  the value for tb_subscribe_detail.platform_type
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public void setPlatformType(Integer platformType) {
		this.platformType = platformType;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_subscribe_detail.content_type
	 * @return  the value of tb_subscribe_detail.content_type
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public Integer getContentType() {
		return contentType;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_subscribe_detail.content_type
	 * @param contentType  the value for tb_subscribe_detail.content_type
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public void setContentType(Integer contentType) {
		this.contentType = contentType;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_subscribe_detail.status
	 * @return  the value of tb_subscribe_detail.status
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public Integer getStatus() {
		return status;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_subscribe_detail.status
	 * @param status  the value for tb_subscribe_detail.status
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_subscribe_detail.weight
	 * @return  the value of tb_subscribe_detail.weight
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public Integer getWeight() {
		return weight;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_subscribe_detail.weight
	 * @param weight  the value for tb_subscribe_detail.weight
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public void setWeight(Integer weight) {
		this.weight = weight;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_subscribe_detail.operator
	 * @return  the value of tb_subscribe_detail.operator
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public Long getOperator() {
		return operator;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_subscribe_detail.operator
	 * @param operator  the value for tb_subscribe_detail.operator
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public void setOperator(Long operator) {
		this.operator = operator;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_subscribe_detail.create_time
	 * @return  the value of tb_subscribe_detail.create_time
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_subscribe_detail.create_time
	 * @param createTime  the value for tb_subscribe_detail.create_time
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_subscribe_detail.update_time
	 * @return  the value of tb_subscribe_detail.update_time
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public Date getUpdateTime() {
		return updateTime;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_subscribe_detail.update_time
	 * @param updateTime  the value for tb_subscribe_detail.update_time
	 * @mbggenerated  Mon Aug 31 17:40:31 CST 2015
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	
	
	
	public String getTitleOrHtmlUrl() {
		return titleOrHtmlUrl;
	}
	public void setTitleOrHtmlUrl(String titleOrHtmlUrl) {
		this.titleOrHtmlUrl = titleOrHtmlUrl;
	}




	/**
	 * 
	 */
	private static final long serialVersionUID = -4352941636898651700L;
	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
	}
}